
// File generated by Wsutil Compiler version 1.0095 
#include <WebServices.h>
#include "EpicWareWeb.Models.xsd.h"

typedef struct _EpicWareWeb_Models_xsdLocalDefinitions 
{
    struct  // global types
    {
        char unused;
        struct  // User
        {
            WS_FIELD_DESCRIPTION UserProfileID;
            WS_FIELD_DESCRIPTION active;
            WS_FIELD_DESCRIPTION email;
            struct  // Language
            {
                WS_FIELD_DESCRIPTION languageID;
                WS_FIELD_DESCRIPTION name;
                WS_FIELD_DESCRIPTION* LanguageFields [2]; 
            } Languagedescs; // end of Language
            WS_FIELD_DESCRIPTION language;
            struct  // Connection
            {
                WS_FIELD_DESCRIPTION Owner;
                WS_FIELD_DESCRIPTION connectionID;
                WS_FIELD_DESCRIPTION strenght;
                struct  // TagConnection
                {
                    WS_FIELD_DESCRIPTION tag;
                    WS_FIELD_DESCRIPTION tagConnectionID;
                    WS_FIELD_DESCRIPTION* TagConnectionFields [2]; 
                } TagConnectiondescs; // end of TagConnection
                WS_FIELD_DESCRIPTION tagConnection;
                WS_FIELD_DESCRIPTION userConnected;
                WS_FIELD_DESCRIPTION* ConnectionFields [5]; 
            } Connectiondescs; // end of Connection
            WS_FIELD_DESCRIPTION listConnections;
            struct  // Mission
            {
                WS_FIELD_DESCRIPTION description;
                WS_FIELD_DESCRIPTION level;
                WS_FIELD_DESCRIPTION missionID;
                WS_FIELD_DESCRIPTION* MissionFields [3]; 
            } Missiondescs; // end of Mission
            WS_FIELD_DESCRIPTION missions;
            struct  // Mood
            {
                WS_FIELD_DESCRIPTION moodID;
                WS_FIELD_DESCRIPTION name;
                WS_FIELD_DESCRIPTION* MoodFields [2]; 
            } Mooddescs; // end of Mood
            WS_FIELD_DESCRIPTION mood;
            struct  // Notification
            {
                WS_FIELD_DESCRIPTION message;
                WS_FIELD_DESCRIPTION notificationID;
                struct  // NotificationType
                {
                    WS_FIELD_DESCRIPTION notificationTypeID;
                    WS_FIELD_DESCRIPTION resultLink;
                    WS_FIELD_DESCRIPTION type;
                    WS_FIELD_DESCRIPTION* NotificationTypeFields [3]; 
                } NotificationTypedescs; // end of NotificationType
                WS_FIELD_DESCRIPTION notificationType;
                WS_FIELD_DESCRIPTION read;
                WS_FIELD_DESCRIPTION time;
                WS_FIELD_DESCRIPTION* NotificationFields [5]; 
            } Notificationdescs; // end of Notification
            WS_FIELD_DESCRIPTION notifications;
            struct  // ScoreUser
            {
                WS_FIELD_DESCRIPTION scoreUserID;
                WS_FIELD_DESCRIPTION* ScoreUserFields [1]; 
            } ScoreUserdescs; // end of ScoreUser
            WS_FIELD_DESCRIPTION scores;
            WS_FIELD_DESCRIPTION userID;
            struct  // Profile
            {
                WS_FIELD_DESCRIPTION birthday;
                struct  // Country
                {
                    WS_FIELD_DESCRIPTION countryID;
                    WS_FIELD_DESCRIPTION name;
                    WS_FIELD_DESCRIPTION* CountryFields [2]; 
                } Countrydescs; // end of Country
                WS_FIELD_DESCRIPTION country;
                WS_FIELD_DESCRIPTION facebookProfile;
                WS_FIELD_DESCRIPTION gender;
                WS_FIELD_DESCRIPTION lastName;
                WS_FIELD_DESCRIPTION linkedinProfile;
                WS_FIELD_DESCRIPTION name;
                WS_FIELD_DESCRIPTION nickname;
                WS_FIELD_DESCRIPTION pathImg;
                WS_FIELD_DESCRIPTION phoneNumber;
                WS_FIELD_DESCRIPTION profileID;
                WS_FIELD_DESCRIPTION twitterProfile;
                WS_FIELD_DESCRIPTION* ProfileFields [12]; 
            } Profiledescs; // end of Profile
            WS_FIELD_DESCRIPTION userProfile;
            struct  // Tag
            {
                WS_FIELD_DESCRIPTION tag;
                WS_FIELD_DESCRIPTION tagID;
                WS_FIELD_DESCRIPTION* TagFields [2]; 
            } Tagdescs; // end of Tag
            WS_FIELD_DESCRIPTION userTags;
            WS_FIELD_DESCRIPTION* UserFields [12]; 
        } Userdescs; // end of User
        struct  // ArrayOfConnection
        {
            WS_FIELD_DESCRIPTION Connection;
            WS_FIELD_DESCRIPTION* ArrayOfConnectionFields [1]; 
        } ArrayOfConnectiondescs; // end of ArrayOfConnection
        struct  // ArrayOfMission
        {
            WS_FIELD_DESCRIPTION Mission;
            WS_FIELD_DESCRIPTION* ArrayOfMissionFields [1]; 
        } ArrayOfMissiondescs; // end of ArrayOfMission
        struct  // ArrayOfNotification
        {
            WS_FIELD_DESCRIPTION Notification;
            WS_FIELD_DESCRIPTION* ArrayOfNotificationFields [1]; 
        } ArrayOfNotificationdescs; // end of ArrayOfNotification
        struct  // ArrayOfScoreUser
        {
            WS_FIELD_DESCRIPTION ScoreUser;
            WS_FIELD_DESCRIPTION* ArrayOfScoreUserFields [1]; 
        } ArrayOfScoreUserdescs; // end of ArrayOfScoreUser
        struct  // ArrayOfTag
        {
            WS_FIELD_DESCRIPTION Tag;
            WS_FIELD_DESCRIPTION* ArrayOfTagFields [1]; 
        } ArrayOfTagdescs; // end of ArrayOfTag
        struct  // ArrayOfUser
        {
            WS_FIELD_DESCRIPTION User;
            WS_FIELD_DESCRIPTION* ArrayOfUserFields [1]; 
        } ArrayOfUserdescs; // end of ArrayOfUser
    } globalTypes;  // end of global types
    struct  // XML dictionary
    {
        struct  // XML string list
        {
            WS_XML_STRING UserTypeName;  // User
            WS_XML_STRING UserTypeNamespace;  // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_XML_STRING UserUserProfileIDLocalName;  // UserProfileID
            WS_XML_STRING UseractiveLocalName;  // active
            WS_XML_STRING UseremailLocalName;  // email
            WS_XML_STRING LanguageTypeName;  // Language
            WS_XML_STRING LanguagelanguageIDLocalName;  // languageID
            WS_XML_STRING LanguagenameLocalName;  // name
            WS_XML_STRING UserlanguageLocalName;  // language
            WS_XML_STRING ConnectionTypeName;  // Connection
            WS_XML_STRING ConnectionOwnerLocalName;  // Owner
            WS_XML_STRING ConnectionconnectionIDLocalName;  // connectionID
            WS_XML_STRING ConnectionstrenghtLocalName;  // strenght
            WS_XML_STRING TagConnectionTypeName;  // TagConnection
            WS_XML_STRING TagConnectiontagLocalName;  // tag
            WS_XML_STRING TagConnectiontagConnectionIDLocalName;  // tagConnectionID
            WS_XML_STRING ConnectiontagConnectionLocalName;  // tagConnection
            WS_XML_STRING ConnectionuserConnectedLocalName;  // userConnected
            WS_XML_STRING UserlistConnectionsWrapperName;  // listConnections
            WS_XML_STRING MissionTypeName;  // Mission
            WS_XML_STRING MissiondescriptionLocalName;  // description
            WS_XML_STRING MissionlevelLocalName;  // level
            WS_XML_STRING MissionmissionIDLocalName;  // missionID
            WS_XML_STRING UsermissionsWrapperName;  // missions
            WS_XML_STRING MoodTypeName;  // Mood
            WS_XML_STRING MoodmoodIDLocalName;  // moodID
            WS_XML_STRING UsermoodLocalName;  // mood
            WS_XML_STRING NotificationTypeName;  // Notification
            WS_XML_STRING NotificationmessageLocalName;  // message
            WS_XML_STRING NotificationnotificationIDLocalName;  // notificationID
            WS_XML_STRING NotificationTypeTypeName;  // NotificationType
            WS_XML_STRING NotificationTypenotificationTypeIDLocalName;  // notificationTypeID
            WS_XML_STRING NotificationTyperesultLinkLocalName;  // resultLink
            WS_XML_STRING NotificationTypetypeLocalName;  // type
            WS_XML_STRING NotificationnotificationTypeLocalName;  // notificationType
            WS_XML_STRING NotificationreadLocalName;  // read
            WS_XML_STRING NotificationtimeLocalName;  // time
            WS_XML_STRING UsernotificationsWrapperName;  // notifications
            WS_XML_STRING ScoreUserTypeName;  // ScoreUser
            WS_XML_STRING ScoreUserscoreUserIDLocalName;  // scoreUserID
            WS_XML_STRING UserscoresWrapperName;  // scores
            WS_XML_STRING UseruserIDLocalName;  // userID
            WS_XML_STRING ProfileTypeName;  // Profile
            WS_XML_STRING ProfilebirthdayLocalName;  // birthday
            WS_XML_STRING CountryTypeName;  // Country
            WS_XML_STRING CountrycountryIDLocalName;  // countryID
            WS_XML_STRING ProfilecountryLocalName;  // country
            WS_XML_STRING ProfilefacebookProfileLocalName;  // facebookProfile
            WS_XML_STRING ProfilegenderLocalName;  // gender
            WS_XML_STRING ProfilelastNameLocalName;  // lastName
            WS_XML_STRING ProfilelinkedinProfileLocalName;  // linkedinProfile
            WS_XML_STRING ProfilenicknameLocalName;  // nickname
            WS_XML_STRING ProfilepathImgLocalName;  // pathImg
            WS_XML_STRING ProfilephoneNumberLocalName;  // phoneNumber
            WS_XML_STRING ProfileprofileIDLocalName;  // profileID
            WS_XML_STRING ProfiletwitterProfileLocalName;  // twitterProfile
            WS_XML_STRING UseruserProfileLocalName;  // userProfile
            WS_XML_STRING TagTypeName;  // Tag
            WS_XML_STRING TagtagIDLocalName;  // tagID
            WS_XML_STRING UseruserTagsWrapperName;  // userTags
            WS_XML_STRING ArrayOfConnectionTypeName;  // ArrayOfConnection
            WS_XML_STRING ArrayOfMissionTypeName;  // ArrayOfMission
            WS_XML_STRING ArrayOfNotificationTypeName;  // ArrayOfNotification
            WS_XML_STRING ArrayOfScoreUserTypeName;  // ArrayOfScoreUser
            WS_XML_STRING ArrayOfTagTypeName;  // ArrayOfTag
            WS_XML_STRING ArrayOfUserTypeName;  // ArrayOfUser
        } xmlStrings;  // end of XML string list
        WS_XML_DICTIONARY dict;
    } dictionary;  // end of XML dictionary
} _EpicWareWeb_Models_xsdLocalDefinitions;

const static _EpicWareWeb_Models_xsdLocalDefinitions EpicWareWeb_Models_xsdLocalDefinitions =
{
    { // global types
        0,
        {  // User
            {  // field description for UserProfileID
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserUserProfileIDLocalName, // UserProfileID
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_INT32_TYPE,
            0,
            WsOffsetOf(User, UserProfileID),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for UserProfileID
            {  // field description for active
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UseractiveLocalName, // active
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_BOOL_TYPE,
            0,
            WsOffsetOf(User, active),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for active
            {  // field description for email
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UseremailLocalName, // email
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(User, email),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for email
            {  // Language
                {  // field description for languageID
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.LanguagelanguageIDLocalName, // languageID
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_INT32_TYPE,
                0,
                WsOffsetOf(Language, languageID),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for languageID
                {  // field description for name
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.LanguagenameLocalName, // name
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(Language, name),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for name
                {  // fields description for Language
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Languagedescs.languageID,
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Languagedescs.name,
                },
            },    // Language
            {  // field description for language
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserlanguageLocalName, // language
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.Language,
            WsOffsetOf(User, language),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for language
            {  // Connection
                {  // field description for Owner
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ConnectionOwnerLocalName, // Owner
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_STRUCT_TYPE,
                (void*)&EpicWareWeb_Models_xsd.globalTypes.User,
                WsOffsetOf(Connection, Owner),
                WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for Owner
                {  // field description for connectionID
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ConnectionconnectionIDLocalName, // connectionID
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_INT32_TYPE,
                0,
                WsOffsetOf(Connection, connectionID),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for connectionID
                {  // field description for strenght
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ConnectionstrenghtLocalName, // strenght
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_INT32_TYPE,
                0,
                WsOffsetOf(Connection, strenght),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for strenght
                {  // TagConnection
                    {  // field description for tag
                    WS_ELEMENT_FIELD_MAPPING,
                    (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.TagConnectiontagLocalName, // tag
                    (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                    WS_WSZ_TYPE,
                    0,
                    WsOffsetOf(TagConnection, tag),
                     WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                    0,
                    0xffffffff
                    },    // end of field description for tag
                    {  // field description for tagConnectionID
                    WS_ELEMENT_FIELD_MAPPING,
                    (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.TagConnectiontagConnectionIDLocalName, // tagConnectionID
                    (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                    WS_INT32_TYPE,
                    0,
                    WsOffsetOf(TagConnection, tagConnectionID),
                     WS_FIELD_OPTIONAL,
                    0,
                    0xffffffff
                    },    // end of field description for tagConnectionID
                    {  // fields description for TagConnection
                    (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Connectiondescs.TagConnectiondescs.tag,
                    (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Connectiondescs.TagConnectiondescs.tagConnectionID,
                    },
                },    // TagConnection
                {  // field description for tagConnection
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ConnectiontagConnectionLocalName, // tagConnection
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_STRUCT_TYPE,
                (void*)&EpicWareWeb_Models_xsd.globalTypes.TagConnection,
                WsOffsetOf(Connection, tagConnection),
                WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for tagConnection
                {  // field description for userConnected
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ConnectionuserConnectedLocalName, // userConnected
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_STRUCT_TYPE,
                (void*)&EpicWareWeb_Models_xsd.globalTypes.User,
                WsOffsetOf(Connection, userConnected),
                WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for userConnected
                {  // fields description for Connection
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Connectiondescs.Owner,
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Connectiondescs.connectionID,
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Connectiondescs.strenght,
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Connectiondescs.tagConnection,
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Connectiondescs.userConnected,
                },
            },    // Connection
            {  // field description for listConnections
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserlistConnectionsWrapperName, // listConnections
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.Connection,
            WsOffsetOf(User, listConnections),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(User, listConnectionsCount),
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ConnectionTypeName, // Connection
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            0,
            },    // end of field description for listConnections
            {  // Mission
                {  // field description for description
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.MissiondescriptionLocalName, // description
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(Mission, description),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for description
                {  // field description for level
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.MissionlevelLocalName, // level
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_INT32_TYPE,
                0,
                WsOffsetOf(Mission, level),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for level
                {  // field description for missionID
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.MissionmissionIDLocalName, // missionID
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_INT32_TYPE,
                0,
                WsOffsetOf(Mission, missionID),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for missionID
                {  // fields description for Mission
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Missiondescs.description,
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Missiondescs.level,
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Missiondescs.missionID,
                },
            },    // Mission
            {  // field description for missions
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UsermissionsWrapperName, // missions
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.Mission,
            WsOffsetOf(User, missions),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(User, missionsCount),
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.MissionTypeName, // Mission
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            0,
            },    // end of field description for missions
            {  // Mood
                {  // field description for moodID
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.MoodmoodIDLocalName, // moodID
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_INT32_TYPE,
                0,
                WsOffsetOf(Mood, moodID),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for moodID
                {  // field description for name
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.LanguagenameLocalName, // name
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(Mood, name),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for name
                {  // fields description for Mood
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Mooddescs.moodID,
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Mooddescs.name,
                },
            },    // Mood
            {  // field description for mood
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UsermoodLocalName, // mood
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.Mood,
            WsOffsetOf(User, mood),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for mood
            {  // Notification
                {  // field description for message
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.NotificationmessageLocalName, // message
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(Notification, message),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for message
                {  // field description for notificationID
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.NotificationnotificationIDLocalName, // notificationID
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_INT32_TYPE,
                0,
                WsOffsetOf(Notification, notificationID),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for notificationID
                {  // NotificationType
                    {  // field description for notificationTypeID
                    WS_ELEMENT_FIELD_MAPPING,
                    (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.NotificationTypenotificationTypeIDLocalName, // notificationTypeID
                    (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                    WS_INT32_TYPE,
                    0,
                    WsOffsetOf(NotificationType, notificationTypeID),
                     WS_FIELD_OPTIONAL,
                    0,
                    0xffffffff
                    },    // end of field description for notificationTypeID
                    {  // field description for resultLink
                    WS_ELEMENT_FIELD_MAPPING,
                    (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.NotificationTyperesultLinkLocalName, // resultLink
                    (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                    WS_WSZ_TYPE,
                    0,
                    WsOffsetOf(NotificationType, resultLink),
                     WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                    0,
                    0xffffffff
                    },    // end of field description for resultLink
                    {  // field description for type
                    WS_ELEMENT_FIELD_MAPPING,
                    (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.NotificationTypetypeLocalName, // type
                    (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                    WS_WSZ_TYPE,
                    0,
                    WsOffsetOf(NotificationType, type),
                     WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                    0,
                    0xffffffff
                    },    // end of field description for type
                    {  // fields description for NotificationType
                    (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Notificationdescs.NotificationTypedescs.notificationTypeID,
                    (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Notificationdescs.NotificationTypedescs.resultLink,
                    (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Notificationdescs.NotificationTypedescs.type,
                    },
                },    // NotificationType
                {  // field description for notificationType
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.NotificationnotificationTypeLocalName, // notificationType
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_STRUCT_TYPE,
                (void*)&EpicWareWeb_Models_xsd.globalTypes.NotificationType,
                WsOffsetOf(Notification, notificationType),
                WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for notificationType
                {  // field description for read
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.NotificationreadLocalName, // read
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_BOOL_TYPE,
                0,
                WsOffsetOf(Notification, read),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for read
                {  // field description for time
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.NotificationtimeLocalName, // time
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_DATETIME_TYPE,
                0,
                WsOffsetOf(Notification, time),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for time
                {  // fields description for Notification
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Notificationdescs.message,
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Notificationdescs.notificationID,
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Notificationdescs.notificationType,
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Notificationdescs.read,
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Notificationdescs.time,
                },
            },    // Notification
            {  // field description for notifications
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UsernotificationsWrapperName, // notifications
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.Notification,
            WsOffsetOf(User, notifications),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(User, notificationsCount),
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.NotificationTypeName, // Notification
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            0,
            },    // end of field description for notifications
            {  // ScoreUser
                {  // field description for scoreUserID
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ScoreUserscoreUserIDLocalName, // scoreUserID
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_INT32_TYPE,
                0,
                WsOffsetOf(ScoreUser, scoreUserID),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for scoreUserID
                {  // fields description for ScoreUser
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.ScoreUserdescs.scoreUserID,
                },
            },    // ScoreUser
            {  // field description for scores
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserscoresWrapperName, // scores
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.ScoreUser,
            WsOffsetOf(User, scores),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(User, scoresCount),
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ScoreUserTypeName, // ScoreUser
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            0,
            },    // end of field description for scores
            {  // field description for userID
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UseruserIDLocalName, // userID
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_INT32_TYPE,
            0,
            WsOffsetOf(User, userID),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for userID
            {  // Profile
                {  // field description for birthday
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ProfilebirthdayLocalName, // birthday
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_DATETIME_TYPE,
                0,
                WsOffsetOf(Profile, birthday),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for birthday
                {  // Country
                    {  // field description for countryID
                    WS_ELEMENT_FIELD_MAPPING,
                    (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.CountrycountryIDLocalName, // countryID
                    (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                    WS_INT32_TYPE,
                    0,
                    WsOffsetOf(Country, countryID),
                     WS_FIELD_OPTIONAL,
                    0,
                    0xffffffff
                    },    // end of field description for countryID
                    {  // field description for name
                    WS_ELEMENT_FIELD_MAPPING,
                    (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.LanguagenameLocalName, // name
                    (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                    WS_WSZ_TYPE,
                    0,
                    WsOffsetOf(Country, name),
                     WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                    0,
                    0xffffffff
                    },    // end of field description for name
                    {  // fields description for Country
                    (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Profiledescs.Countrydescs.countryID,
                    (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Profiledescs.Countrydescs.name,
                    },
                },    // Country
                {  // field description for country
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ProfilecountryLocalName, // country
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_STRUCT_TYPE,
                (void*)&EpicWareWeb_Models_xsd.globalTypes.Country,
                WsOffsetOf(Profile, country),
                WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for country
                {  // field description for facebookProfile
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ProfilefacebookProfileLocalName, // facebookProfile
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(Profile, facebookProfile),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for facebookProfile
                {  // field description for gender
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ProfilegenderLocalName, // gender
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(Profile, gender),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for gender
                {  // field description for lastName
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ProfilelastNameLocalName, // lastName
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(Profile, lastName),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for lastName
                {  // field description for linkedinProfile
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ProfilelinkedinProfileLocalName, // linkedinProfile
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(Profile, linkedinProfile),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for linkedinProfile
                {  // field description for name
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.LanguagenameLocalName, // name
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(Profile, name),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for name
                {  // field description for nickname
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ProfilenicknameLocalName, // nickname
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(Profile, nickname),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for nickname
                {  // field description for pathImg
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ProfilepathImgLocalName, // pathImg
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(Profile, pathImg),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for pathImg
                {  // field description for phoneNumber
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ProfilephoneNumberLocalName, // phoneNumber
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_INT32_TYPE,
                0,
                WsOffsetOf(Profile, phoneNumber),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for phoneNumber
                {  // field description for profileID
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ProfileprofileIDLocalName, // profileID
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_INT32_TYPE,
                0,
                WsOffsetOf(Profile, profileID),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for profileID
                {  // field description for twitterProfile
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ProfiletwitterProfileLocalName, // twitterProfile
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(Profile, twitterProfile),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for twitterProfile
                {  // fields description for Profile
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Profiledescs.birthday,
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Profiledescs.country,
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Profiledescs.facebookProfile,
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Profiledescs.gender,
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Profiledescs.lastName,
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Profiledescs.linkedinProfile,
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Profiledescs.name,
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Profiledescs.nickname,
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Profiledescs.pathImg,
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Profiledescs.phoneNumber,
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Profiledescs.profileID,
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Profiledescs.twitterProfile,
                },
            },    // Profile
            {  // field description for userProfile
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UseruserProfileLocalName, // userProfile
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.Profile,
            WsOffsetOf(User, userProfile),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for userProfile
            {  // Tag
                {  // field description for tag
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.TagConnectiontagLocalName, // tag
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(Tag, tag),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for tag
                {  // field description for tagID
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.TagtagIDLocalName, // tagID
                (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
                WS_INT32_TYPE,
                0,
                WsOffsetOf(Tag, tagID),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for tagID
                {  // fields description for Tag
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Tagdescs.tag,
                (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Tagdescs.tagID,
                },
            },    // Tag
            {  // field description for userTags
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UseruserTagsWrapperName, // userTags
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.Tag,
            WsOffsetOf(User, userTags),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(User, userTagsCount),
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.TagTypeName, // Tag
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            0,
            },    // end of field description for userTags
            {  // fields description for User
            (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.UserProfileID,
            (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.active,
            (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.email,
            (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.language,
            (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.listConnections,
            (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.missions,
            (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.mood,
            (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.notifications,
            (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.scores,
            (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.userID,
            (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.userProfile,
            (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.userTags,
            },
        },    // User
        {  // ArrayOfConnection
            {  // field description for Connection
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            0,
            0,
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.Connection,
            WsOffsetOf(ArrayOfConnection, Connection),
            WS_FIELD_POINTER| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(ArrayOfConnection, ConnectionCount),
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ConnectionTypeName, // Connection
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            0,
            },    // end of field description for Connection
            {  // fields description for ArrayOfConnection
            (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.ArrayOfConnectiondescs.Connection,
            },
        },    // ArrayOfConnection
        {  // ArrayOfMission
            {  // field description for Mission
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            0,
            0,
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.Mission,
            WsOffsetOf(ArrayOfMission, Mission),
            WS_FIELD_POINTER| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(ArrayOfMission, MissionCount),
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.MissionTypeName, // Mission
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            0,
            },    // end of field description for Mission
            {  // fields description for ArrayOfMission
            (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.ArrayOfMissiondescs.Mission,
            },
        },    // ArrayOfMission
        {  // ArrayOfNotification
            {  // field description for Notification
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            0,
            0,
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.Notification,
            WsOffsetOf(ArrayOfNotification, Notification),
            WS_FIELD_POINTER| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(ArrayOfNotification, NotificationCount),
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.NotificationTypeName, // Notification
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            0,
            },    // end of field description for Notification
            {  // fields description for ArrayOfNotification
            (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.ArrayOfNotificationdescs.Notification,
            },
        },    // ArrayOfNotification
        {  // ArrayOfScoreUser
            {  // field description for ScoreUser
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            0,
            0,
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.ScoreUser,
            WsOffsetOf(ArrayOfScoreUser, ScoreUser),
            WS_FIELD_POINTER| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(ArrayOfScoreUser, ScoreUserCount),
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ScoreUserTypeName, // ScoreUser
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            0,
            },    // end of field description for ScoreUser
            {  // fields description for ArrayOfScoreUser
            (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.ArrayOfScoreUserdescs.ScoreUser,
            },
        },    // ArrayOfScoreUser
        {  // ArrayOfTag
            {  // field description for Tag
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            0,
            0,
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.Tag,
            WsOffsetOf(ArrayOfTag, Tag),
            WS_FIELD_POINTER| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(ArrayOfTag, TagCount),
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.TagTypeName, // Tag
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            0,
            },    // end of field description for Tag
            {  // fields description for ArrayOfTag
            (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.ArrayOfTagdescs.Tag,
            },
        },    // ArrayOfTag
        {  // ArrayOfUser
            {  // field description for User
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            0,
            0,
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.User,
            WsOffsetOf(ArrayOfUser, User),
            WS_FIELD_POINTER| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(ArrayOfUser, UserCount),
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeName, // User
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            0,
            },    // end of field description for User
            {  // fields description for ArrayOfUser
            (WS_FIELD_DESCRIPTION*)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.ArrayOfUserdescs.User,
            },
        },    // ArrayOfUser
    }, // end of global types
    {  // dictionary 
        {  // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("User",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.datacontract.org/2004/07/EpicWareWeb.Models",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("UserProfileID",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("active",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("email",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("Language",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("languageID",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("name",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 7),
            WS_XML_STRING_DICTIONARY_VALUE("language",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 8),
            WS_XML_STRING_DICTIONARY_VALUE("Connection",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 9),
            WS_XML_STRING_DICTIONARY_VALUE("Owner",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 10),
            WS_XML_STRING_DICTIONARY_VALUE("connectionID",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 11),
            WS_XML_STRING_DICTIONARY_VALUE("strenght",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 12),
            WS_XML_STRING_DICTIONARY_VALUE("TagConnection",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 13),
            WS_XML_STRING_DICTIONARY_VALUE("tag",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 14),
            WS_XML_STRING_DICTIONARY_VALUE("tagConnectionID",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 15),
            WS_XML_STRING_DICTIONARY_VALUE("tagConnection",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 16),
            WS_XML_STRING_DICTIONARY_VALUE("userConnected",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 17),
            WS_XML_STRING_DICTIONARY_VALUE("listConnections",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 18),
            WS_XML_STRING_DICTIONARY_VALUE("Mission",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 19),
            WS_XML_STRING_DICTIONARY_VALUE("description",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 20),
            WS_XML_STRING_DICTIONARY_VALUE("level",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 21),
            WS_XML_STRING_DICTIONARY_VALUE("missionID",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 22),
            WS_XML_STRING_DICTIONARY_VALUE("missions",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 23),
            WS_XML_STRING_DICTIONARY_VALUE("Mood",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 24),
            WS_XML_STRING_DICTIONARY_VALUE("moodID",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 25),
            WS_XML_STRING_DICTIONARY_VALUE("mood",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 26),
            WS_XML_STRING_DICTIONARY_VALUE("Notification",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 27),
            WS_XML_STRING_DICTIONARY_VALUE("message",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 28),
            WS_XML_STRING_DICTIONARY_VALUE("notificationID",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 29),
            WS_XML_STRING_DICTIONARY_VALUE("NotificationType",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 30),
            WS_XML_STRING_DICTIONARY_VALUE("notificationTypeID",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 31),
            WS_XML_STRING_DICTIONARY_VALUE("resultLink",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 32),
            WS_XML_STRING_DICTIONARY_VALUE("type",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 33),
            WS_XML_STRING_DICTIONARY_VALUE("notificationType",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 34),
            WS_XML_STRING_DICTIONARY_VALUE("read",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 35),
            WS_XML_STRING_DICTIONARY_VALUE("time",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 36),
            WS_XML_STRING_DICTIONARY_VALUE("notifications",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 37),
            WS_XML_STRING_DICTIONARY_VALUE("ScoreUser",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 38),
            WS_XML_STRING_DICTIONARY_VALUE("scoreUserID",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 39),
            WS_XML_STRING_DICTIONARY_VALUE("scores",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 40),
            WS_XML_STRING_DICTIONARY_VALUE("userID",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 41),
            WS_XML_STRING_DICTIONARY_VALUE("Profile",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 42),
            WS_XML_STRING_DICTIONARY_VALUE("birthday",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 43),
            WS_XML_STRING_DICTIONARY_VALUE("Country",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 44),
            WS_XML_STRING_DICTIONARY_VALUE("countryID",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 45),
            WS_XML_STRING_DICTIONARY_VALUE("country",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 46),
            WS_XML_STRING_DICTIONARY_VALUE("facebookProfile",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 47),
            WS_XML_STRING_DICTIONARY_VALUE("gender",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 48),
            WS_XML_STRING_DICTIONARY_VALUE("lastName",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 49),
            WS_XML_STRING_DICTIONARY_VALUE("linkedinProfile",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 50),
            WS_XML_STRING_DICTIONARY_VALUE("nickname",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 51),
            WS_XML_STRING_DICTIONARY_VALUE("pathImg",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 52),
            WS_XML_STRING_DICTIONARY_VALUE("phoneNumber",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 53),
            WS_XML_STRING_DICTIONARY_VALUE("profileID",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 54),
            WS_XML_STRING_DICTIONARY_VALUE("twitterProfile",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 55),
            WS_XML_STRING_DICTIONARY_VALUE("userProfile",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 56),
            WS_XML_STRING_DICTIONARY_VALUE("Tag",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 57),
            WS_XML_STRING_DICTIONARY_VALUE("tagID",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 58),
            WS_XML_STRING_DICTIONARY_VALUE("userTags",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 59),
            WS_XML_STRING_DICTIONARY_VALUE("ArrayOfConnection",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 60),
            WS_XML_STRING_DICTIONARY_VALUE("ArrayOfMission",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 61),
            WS_XML_STRING_DICTIONARY_VALUE("ArrayOfNotification",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 62),
            WS_XML_STRING_DICTIONARY_VALUE("ArrayOfScoreUser",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 63),
            WS_XML_STRING_DICTIONARY_VALUE("ArrayOfTag",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 64),
            WS_XML_STRING_DICTIONARY_VALUE("ArrayOfUser",&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.dict, 65),
        },  // end of xmlStrings
        
        {  // EpicWareWeb_Models_xsddictionary
          // 5d2ae36c-fa5d-4002-a467-e33ca80b6300 
        { 0x5d2ae36c, 0xfa5d, 0x4002, { 0xa4, 0x67, 0xe3,0x3c, 0xa8, 0x0b, 0x63, 0x00 } },
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings,
        66,
        TRUE,
        },
    },  //  end of dictionary
}; //  end of EpicWareWeb_Models_xsdLocalDefinitions

const _EpicWareWeb_Models_xsd EpicWareWeb_Models_xsd =
{
    {  // globalTypes
        {
        sizeof(User),
        __alignof(User),
        (WS_FIELD_DESCRIPTION**)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.UserFields,
        WsCountOf(EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.UserFields),
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeName, // User
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
        0,
        0,
        0,
        },   // end of struct description for User
        {
        sizeof(Language),
        __alignof(Language),
        (WS_FIELD_DESCRIPTION**)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Languagedescs.LanguageFields,
        WsCountOf(EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Languagedescs.LanguageFields),
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.LanguageTypeName, // Language
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
        0,
        0,
        0,
        },   // end of struct description for Language
        {
        sizeof(ArrayOfConnection),
        __alignof(ArrayOfConnection),
        (WS_FIELD_DESCRIPTION**)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.ArrayOfConnectiondescs.ArrayOfConnectionFields,
        WsCountOf(EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.ArrayOfConnectiondescs.ArrayOfConnectionFields),
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfConnectionTypeName, // ArrayOfConnection
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
        0,
        0,
        0,
        },   // end of struct description for ArrayOfConnection
        {
        sizeof(Connection),
        __alignof(Connection),
        (WS_FIELD_DESCRIPTION**)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Connectiondescs.ConnectionFields,
        WsCountOf(EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Connectiondescs.ConnectionFields),
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ConnectionTypeName, // Connection
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
        0,
        0,
        0,
        },   // end of struct description for Connection
        {
        sizeof(TagConnection),
        __alignof(TagConnection),
        (WS_FIELD_DESCRIPTION**)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Connectiondescs.TagConnectiondescs.TagConnectionFields,
        WsCountOf(EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Connectiondescs.TagConnectiondescs.TagConnectionFields),
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.TagConnectionTypeName, // TagConnection
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
        0,
        0,
        0,
        },   // end of struct description for TagConnection
        {
        sizeof(ArrayOfMission),
        __alignof(ArrayOfMission),
        (WS_FIELD_DESCRIPTION**)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.ArrayOfMissiondescs.ArrayOfMissionFields,
        WsCountOf(EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.ArrayOfMissiondescs.ArrayOfMissionFields),
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfMissionTypeName, // ArrayOfMission
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
        0,
        0,
        0,
        },   // end of struct description for ArrayOfMission
        {
        sizeof(Mission),
        __alignof(Mission),
        (WS_FIELD_DESCRIPTION**)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Missiondescs.MissionFields,
        WsCountOf(EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Missiondescs.MissionFields),
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.MissionTypeName, // Mission
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
        0,
        0,
        0,
        },   // end of struct description for Mission
        {
        sizeof(Mood),
        __alignof(Mood),
        (WS_FIELD_DESCRIPTION**)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Mooddescs.MoodFields,
        WsCountOf(EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Mooddescs.MoodFields),
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.MoodTypeName, // Mood
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
        0,
        0,
        0,
        },   // end of struct description for Mood
        {
        sizeof(ArrayOfNotification),
        __alignof(ArrayOfNotification),
        (WS_FIELD_DESCRIPTION**)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.ArrayOfNotificationdescs.ArrayOfNotificationFields,
        WsCountOf(EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.ArrayOfNotificationdescs.ArrayOfNotificationFields),
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNotificationTypeName, // ArrayOfNotification
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
        0,
        0,
        0,
        },   // end of struct description for ArrayOfNotification
        {
        sizeof(Notification),
        __alignof(Notification),
        (WS_FIELD_DESCRIPTION**)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Notificationdescs.NotificationFields,
        WsCountOf(EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Notificationdescs.NotificationFields),
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.NotificationTypeName, // Notification
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
        0,
        0,
        0,
        },   // end of struct description for Notification
        {
        sizeof(NotificationType),
        __alignof(NotificationType),
        (WS_FIELD_DESCRIPTION**)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Notificationdescs.NotificationTypedescs.NotificationTypeFields,
        WsCountOf(EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Notificationdescs.NotificationTypedescs.NotificationTypeFields),
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.NotificationTypeTypeName, // NotificationType
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
        0,
        0,
        0,
        },   // end of struct description for NotificationType
        {
        sizeof(ArrayOfScoreUser),
        __alignof(ArrayOfScoreUser),
        (WS_FIELD_DESCRIPTION**)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.ArrayOfScoreUserdescs.ArrayOfScoreUserFields,
        WsCountOf(EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.ArrayOfScoreUserdescs.ArrayOfScoreUserFields),
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfScoreUserTypeName, // ArrayOfScoreUser
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
        0,
        0,
        0,
        },   // end of struct description for ArrayOfScoreUser
        {
        sizeof(ScoreUser),
        __alignof(ScoreUser),
        (WS_FIELD_DESCRIPTION**)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.ScoreUserdescs.ScoreUserFields,
        WsCountOf(EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.ScoreUserdescs.ScoreUserFields),
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ScoreUserTypeName, // ScoreUser
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
        0,
        0,
        0,
        },   // end of struct description for ScoreUser
        {
        sizeof(Profile),
        __alignof(Profile),
        (WS_FIELD_DESCRIPTION**)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Profiledescs.ProfileFields,
        WsCountOf(EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Profiledescs.ProfileFields),
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ProfileTypeName, // Profile
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
        0,
        0,
        0,
        },   // end of struct description for Profile
        {
        sizeof(Country),
        __alignof(Country),
        (WS_FIELD_DESCRIPTION**)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Profiledescs.Countrydescs.CountryFields,
        WsCountOf(EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Profiledescs.Countrydescs.CountryFields),
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.CountryTypeName, // Country
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
        0,
        0,
        0,
        },   // end of struct description for Country
        {
        sizeof(ArrayOfTag),
        __alignof(ArrayOfTag),
        (WS_FIELD_DESCRIPTION**)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.ArrayOfTagdescs.ArrayOfTagFields,
        WsCountOf(EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.ArrayOfTagdescs.ArrayOfTagFields),
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfTagTypeName, // ArrayOfTag
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
        0,
        0,
        0,
        },   // end of struct description for ArrayOfTag
        {
        sizeof(Tag),
        __alignof(Tag),
        (WS_FIELD_DESCRIPTION**)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Tagdescs.TagFields,
        WsCountOf(EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.Userdescs.Tagdescs.TagFields),
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.TagTypeName, // Tag
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
        0,
        0,
        0,
        },   // end of struct description for Tag
        {
        sizeof(ArrayOfUser),
        __alignof(ArrayOfUser),
        (WS_FIELD_DESCRIPTION**)&EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.ArrayOfUserdescs.ArrayOfUserFields,
        WsCountOf(EpicWareWeb_Models_xsdLocalDefinitions.globalTypes.ArrayOfUserdescs.ArrayOfUserFields),
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeName, // ArrayOfUser
        (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
        0,
        0,
        0,
        },   // end of struct description for ArrayOfUser
    },  // globalTypes
    {  // globalElements
        {
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeName, // User
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.User,
        },
        {
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.LanguageTypeName, // Language
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.Language,
        },
        {
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfConnectionTypeName, // ArrayOfConnection
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.ArrayOfConnection,
        },
        {
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ConnectionTypeName, // Connection
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.Connection,
        },
        {
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.TagConnectionTypeName, // TagConnection
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.TagConnection,
        },
        {
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfMissionTypeName, // ArrayOfMission
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.ArrayOfMission,
        },
        {
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.MissionTypeName, // Mission
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.Mission,
        },
        {
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.MoodTypeName, // Mood
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.Mood,
        },
        {
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNotificationTypeName, // ArrayOfNotification
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.ArrayOfNotification,
        },
        {
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.NotificationTypeName, // Notification
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.Notification,
        },
        {
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.NotificationTypeTypeName, // NotificationType
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.NotificationType,
        },
        {
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfScoreUserTypeName, // ArrayOfScoreUser
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.ArrayOfScoreUser,
        },
        {
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ScoreUserTypeName, // ScoreUser
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.ScoreUser,
        },
        {
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ProfileTypeName, // Profile
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.Profile,
        },
        {
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.CountryTypeName, // Country
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.Country,
        },
        {
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfTagTypeName, // ArrayOfTag
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.ArrayOfTag,
        },
        {
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.TagTypeName, // Tag
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.Tag,
        },
        {
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfUserTypeName, // ArrayOfUser
            (WS_XML_STRING*)&EpicWareWeb_Models_xsdLocalDefinitions.dictionary.xmlStrings.UserTypeNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.ArrayOfUser,
        },
    },  // globalElements
}; // end of _EpicWareWeb_Models_xsd
