
// File generated by Wsutil Compiler version 1.0095 
#include <WebServices.h>
#include "EpicWareWeb.Models.xsd.h"
#include "EpicWareWeb.xsd.h"
#include "schemas.microsoft.com.2003.10.Serialization.Arrays.xsd.h"
#include "tempuri.org.xsd.h"

typedef struct _tempuri_org_xsdLocalDefinitions 
{
    struct  // global elements
    {
    char unused;
        struct  // _getNumberUsersResponse
        {
            WS_FIELD_DESCRIPTION getNumberUsersResult;
            WS_FIELD_DESCRIPTION* _getNumberUsersResponseFields [1]; 
        } _getNumberUsersResponsedescs; // end of _getNumberUsersResponse
        struct  // _getNumberDownloadsResponse
        {
            WS_FIELD_DESCRIPTION getNumberDownloadsResult;
            WS_FIELD_DESCRIPTION* _getNumberDownloadsResponseFields [1]; 
        } _getNumberDownloadsResponsedescs; // end of _getNumberDownloadsResponse
        struct  // _getUserByID
        {
            WS_FIELD_DESCRIPTION id;
            WS_FIELD_DESCRIPTION user;
            WS_FIELD_DESCRIPTION pass;
            WS_FIELD_DESCRIPTION* _getUserByIDFields [3]; 
        } _getUserByIDdescs; // end of _getUserByID
        struct  // _getUserByIDResponse
        {
            WS_FIELD_DESCRIPTION getUserByIDResult;
            WS_FIELD_DESCRIPTION* _getUserByIDResponseFields [1]; 
        } _getUserByIDResponsedescs; // end of _getUserByIDResponse
        struct  // _getUserFriendsByUserId
        {
            WS_FIELD_DESCRIPTION id;
            WS_FIELD_DESCRIPTION user;
            WS_FIELD_DESCRIPTION pass;
            WS_FIELD_DESCRIPTION* _getUserFriendsByUserIdFields [3]; 
        } _getUserFriendsByUserIddescs; // end of _getUserFriendsByUserId
        struct  // _getUserFriendsByUserIdResponse
        {
            WS_FIELD_DESCRIPTION getUserFriendsByUserIdResult;
            WS_FIELD_DESCRIPTION* _getUserFriendsByUserIdResponseFields [1]; 
        } _getUserFriendsByUserIdResponsedescs; // end of _getUserFriendsByUserIdResponse
        struct  // _getUserByAutetication
        {
            WS_FIELD_DESCRIPTION user;
            WS_FIELD_DESCRIPTION password;
            WS_FIELD_DESCRIPTION* _getUserByAuteticationFields [2]; 
        } _getUserByAuteticationdescs; // end of _getUserByAutetication
        struct  // _getUserByAuteticationResponse
        {
            WS_FIELD_DESCRIPTION getUserByAuteticationResult;
            WS_FIELD_DESCRIPTION* _getUserByAuteticationResponseFields [1]; 
        } _getUserByAuteticationResponsedescs; // end of _getUserByAuteticationResponse
        struct  // _GetEveryWordResponse
        {
            WS_FIELD_DESCRIPTION GetEveryWordResult;
            WS_FIELD_DESCRIPTION* _GetEveryWordResponseFields [1]; 
        } _GetEveryWordResponsedescs; // end of _GetEveryWordResponse
        struct  // _getAllUsersIDResponse
        {
            WS_FIELD_DESCRIPTION getAllUsersIDResult;
            WS_FIELD_DESCRIPTION* _getAllUsersIDResponseFields [1]; 
        } _getAllUsersIDResponsedescs; // end of _getAllUsersIDResponse
        struct  // _getConnectioStrenght
        {
            WS_FIELD_DESCRIPTION id1;
            WS_FIELD_DESCRIPTION id2;
            WS_FIELD_DESCRIPTION* _getConnectioStrenghtFields [2]; 
        } _getConnectioStrenghtdescs; // end of _getConnectioStrenght
        struct  // _getConnectioStrenghtResponse
        {
            WS_FIELD_DESCRIPTION getConnectioStrenghtResult;
            WS_FIELD_DESCRIPTION* _getConnectioStrenghtResponseFields [1]; 
        } _getConnectioStrenghtResponsedescs; // end of _getConnectioStrenghtResponse
    } globalElements;  // end of global elements
    struct  // XML dictionary
    {
        struct  // XML string list
        {
            WS_XML_STRING _getNumberUsersTypeName;  // getNumberUsers
            WS_XML_STRING _getNumberUsersTypeNamespace;  // http://tempuri.org/
            WS_XML_STRING _getNumberUsersResponseTypeName;  // getNumberUsersResponse
            WS_XML_STRING _getNumberUsersResponsegetNumberUsersResultLocalName;  // getNumberUsersResult
            WS_XML_STRING _getNumberDownloadsTypeName;  // getNumberDownloads
            WS_XML_STRING _getNumberDownloadsResponseTypeName;  // getNumberDownloadsResponse
            WS_XML_STRING _getNumberDownloadsResponsegetNumberDownloadsResultLocalName;  // getNumberDownloadsResult
            WS_XML_STRING _getUserByIDTypeName;  // getUserByID
            WS_XML_STRING _getUserByIDidLocalName;  // id
            WS_XML_STRING _getUserByIDuserLocalName;  // user
            WS_XML_STRING _getUserByIDpassLocalName;  // pass
            WS_XML_STRING _getUserByIDResponseTypeName;  // getUserByIDResponse
            WS_XML_STRING _getUserByIDResponsegetUserByIDResultLocalName;  // getUserByIDResult
            WS_XML_STRING _getUserFriendsByUserIdTypeName;  // getUserFriendsByUserId
            WS_XML_STRING _getUserFriendsByUserIdResponseTypeName;  // getUserFriendsByUserIdResponse
            WS_XML_STRING _getUserFriendsByUserIdResponsegetUserFriendsByUserIdResultLocalName;  // User
            WS_XML_STRING _getUserFriendsByUserIdResponsegetUserFriendsByUserIdResultNamespace;  // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            WS_XML_STRING _getUserFriendsByUserIdResponsegetUserFriendsByUserIdResultWrapperName;  // getUserFriendsByUserIdResult
            WS_XML_STRING _getUserByAuteticationTypeName;  // getUserByAutetication
            WS_XML_STRING _getUserByAuteticationpasswordLocalName;  // password
            WS_XML_STRING _getUserByAuteticationResponseTypeName;  // getUserByAuteticationResponse
            WS_XML_STRING _getUserByAuteticationResponsegetUserByAuteticationResultLocalName;  // getUserByAuteticationResult
            WS_XML_STRING _GetEveryWordTypeName;  // GetEveryWord
            WS_XML_STRING _GetEveryWordResponseTypeName;  // GetEveryWordResponse
            WS_XML_STRING _GetEveryWordResponseGetEveryWordResultLocalName;  // Word
            WS_XML_STRING _GetEveryWordResponseGetEveryWordResultNamespace;  // http://schemas.datacontract.org/2004/07/EpicWareWeb
            WS_XML_STRING _GetEveryWordResponseGetEveryWordResultWrapperName;  // GetEveryWordResult
            WS_XML_STRING _getAllUsersIDTypeName;  // getAllUsersID
            WS_XML_STRING _getAllUsersIDResponseTypeName;  // getAllUsersIDResponse
            WS_XML_STRING _getAllUsersIDResponsegetAllUsersIDResultLocalName;  // int
            WS_XML_STRING _getAllUsersIDResponsegetAllUsersIDResultNamespace;  // http://schemas.microsoft.com/2003/10/Serialization/Arrays
            WS_XML_STRING _getAllUsersIDResponsegetAllUsersIDResultWrapperName;  // getAllUsersIDResult
            WS_XML_STRING _getConnectioStrenghtTypeName;  // getConnectioStrenght
            WS_XML_STRING _getConnectioStrenghtid1LocalName;  // id1
            WS_XML_STRING _getConnectioStrenghtid2LocalName;  // id2
            WS_XML_STRING _getConnectioStrenghtResponseTypeName;  // getConnectioStrenghtResponse
            WS_XML_STRING _getConnectioStrenghtResponsegetConnectioStrenghtResultLocalName;  // getConnectioStrenghtResult
        } xmlStrings;  // end of XML string list
        WS_XML_DICTIONARY dict;
    } dictionary;  // end of XML dictionary
} _tempuri_org_xsdLocalDefinitions;

const static _tempuri_org_xsdLocalDefinitions tempuri_org_xsdLocalDefinitions =
{
    {  // global elements
        0,
        {  // _getNumberUsersResponse
            {  // field description for getNumberUsersResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersResponsegetNumberUsersResultLocalName, // getNumberUsersResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_getNumberUsersResponse, getNumberUsersResult),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for getNumberUsersResult
            {  // fields description for _getNumberUsersResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._getNumberUsersResponsedescs.getNumberUsersResult,
            },
        },    // _getNumberUsersResponse
        {  // _getNumberDownloadsResponse
            {  // field description for getNumberDownloadsResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberDownloadsResponsegetNumberDownloadsResultLocalName, // getNumberDownloadsResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_getNumberDownloadsResponse, getNumberDownloadsResult),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for getNumberDownloadsResult
            {  // fields description for _getNumberDownloadsResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._getNumberDownloadsResponsedescs.getNumberDownloadsResult,
            },
        },    // _getNumberDownloadsResponse
        {  // _getUserByID
            {  // field description for id
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getUserByIDidLocalName, // id
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_getUserByID, id),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for id
            {  // field description for user
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getUserByIDuserLocalName, // user
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_getUserByID, user),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for user
            {  // field description for pass
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getUserByIDpassLocalName, // pass
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_getUserByID, pass),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for pass
            {  // fields description for _getUserByID
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._getUserByIDdescs.id,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._getUserByIDdescs.user,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._getUserByIDdescs.pass,
            },
        },    // _getUserByID
        {  // _getUserByIDResponse
            {  // field description for getUserByIDResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getUserByIDResponsegetUserByIDResultLocalName, // getUserByIDResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.User,
            WsOffsetOf(_getUserByIDResponse, getUserByIDResult),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for getUserByIDResult
            {  // fields description for _getUserByIDResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._getUserByIDResponsedescs.getUserByIDResult,
            },
        },    // _getUserByIDResponse
        {  // _getUserFriendsByUserId
            {  // field description for id
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getUserByIDidLocalName, // id
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_getUserFriendsByUserId, id),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for id
            {  // field description for user
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getUserByIDuserLocalName, // user
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_getUserFriendsByUserId, user),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for user
            {  // field description for pass
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getUserByIDpassLocalName, // pass
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_getUserFriendsByUserId, pass),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for pass
            {  // fields description for _getUserFriendsByUserId
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._getUserFriendsByUserIddescs.id,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._getUserFriendsByUserIddescs.user,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._getUserFriendsByUserIddescs.pass,
            },
        },    // _getUserFriendsByUserId
        {  // _getUserFriendsByUserIdResponse
            {  // field description for getUserFriendsByUserIdResult
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getUserFriendsByUserIdResponsegetUserFriendsByUserIdResultWrapperName, // getUserFriendsByUserIdResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.User,
            WsOffsetOf(_getUserFriendsByUserIdResponse, getUserFriendsByUserIdResult),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(_getUserFriendsByUserIdResponse, getUserFriendsByUserIdResultCount),
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getUserFriendsByUserIdResponsegetUserFriendsByUserIdResultLocalName, // User
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getUserFriendsByUserIdResponsegetUserFriendsByUserIdResultNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb.Models
            0,
            },    // end of field description for getUserFriendsByUserIdResult
            {  // fields description for _getUserFriendsByUserIdResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._getUserFriendsByUserIdResponsedescs.getUserFriendsByUserIdResult,
            },
        },    // _getUserFriendsByUserIdResponse
        {  // _getUserByAutetication
            {  // field description for user
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getUserByIDuserLocalName, // user
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_getUserByAutetication, user),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for user
            {  // field description for password
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getUserByAuteticationpasswordLocalName, // password
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_getUserByAutetication, password),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for password
            {  // fields description for _getUserByAutetication
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._getUserByAuteticationdescs.user,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._getUserByAuteticationdescs.password,
            },
        },    // _getUserByAutetication
        {  // _getUserByAuteticationResponse
            {  // field description for getUserByAuteticationResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getUserByAuteticationResponsegetUserByAuteticationResultLocalName, // getUserByAuteticationResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_Models_xsd.globalTypes.User,
            WsOffsetOf(_getUserByAuteticationResponse, getUserByAuteticationResult),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for getUserByAuteticationResult
            {  // fields description for _getUserByAuteticationResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._getUserByAuteticationResponsedescs.getUserByAuteticationResult,
            },
        },    // _getUserByAuteticationResponse
        {  // _GetEveryWordResponse
            {  // field description for GetEveryWordResult
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetEveryWordResponseGetEveryWordResultWrapperName, // GetEveryWordResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&EpicWareWeb_xsd.globalTypes.Word,
            WsOffsetOf(_GetEveryWordResponse, GetEveryWordResult),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            WsOffsetOf(_GetEveryWordResponse, GetEveryWordResultCount),
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetEveryWordResponseGetEveryWordResultLocalName, // Word
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetEveryWordResponseGetEveryWordResultNamespace, // http://schemas.datacontract.org/2004/07/EpicWareWeb
            0,
            },    // end of field description for GetEveryWordResult
            {  // fields description for _GetEveryWordResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._GetEveryWordResponsedescs.GetEveryWordResult,
            },
        },    // _GetEveryWordResponse
        {  // _getAllUsersIDResponse
            {  // field description for getAllUsersIDResult
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getAllUsersIDResponsegetAllUsersIDResultWrapperName, // getAllUsersIDResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_getAllUsersIDResponse, getAllUsersIDResult),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            WsOffsetOf(_getAllUsersIDResponse, getAllUsersIDResultCount),
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getAllUsersIDResponsegetAllUsersIDResultLocalName, // int
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getAllUsersIDResponsegetAllUsersIDResultNamespace, // http://schemas.microsoft.com/2003/10/Serialization/Arrays
            0,
            },    // end of field description for getAllUsersIDResult
            {  // fields description for _getAllUsersIDResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._getAllUsersIDResponsedescs.getAllUsersIDResult,
            },
        },    // _getAllUsersIDResponse
        {  // _getConnectioStrenght
            {  // field description for id1
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getConnectioStrenghtid1LocalName, // id1
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_getConnectioStrenght, id1),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for id1
            {  // field description for id2
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getConnectioStrenghtid2LocalName, // id2
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_getConnectioStrenght, id2),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for id2
            {  // fields description for _getConnectioStrenght
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._getConnectioStrenghtdescs.id1,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._getConnectioStrenghtdescs.id2,
            },
        },    // _getConnectioStrenght
        {  // _getConnectioStrenghtResponse
            {  // field description for getConnectioStrenghtResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getConnectioStrenghtResponsegetConnectioStrenghtResultLocalName, // getConnectioStrenghtResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_getConnectioStrenghtResponse, getConnectioStrenghtResult),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for getConnectioStrenghtResult
            {  // fields description for _getConnectioStrenghtResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._getConnectioStrenghtResponsedescs.getConnectioStrenghtResult,
            },
        },    // _getConnectioStrenghtResponse
    }, // end of global elements
    {  // dictionary 
        {  // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("getNumberUsers",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("getNumberUsersResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("getNumberUsersResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("getNumberDownloads",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("getNumberDownloadsResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("getNumberDownloadsResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("getUserByID",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 7),
            WS_XML_STRING_DICTIONARY_VALUE("id",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 8),
            WS_XML_STRING_DICTIONARY_VALUE("user",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 9),
            WS_XML_STRING_DICTIONARY_VALUE("pass",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 10),
            WS_XML_STRING_DICTIONARY_VALUE("getUserByIDResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 11),
            WS_XML_STRING_DICTIONARY_VALUE("getUserByIDResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 12),
            WS_XML_STRING_DICTIONARY_VALUE("getUserFriendsByUserId",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 13),
            WS_XML_STRING_DICTIONARY_VALUE("getUserFriendsByUserIdResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 14),
            WS_XML_STRING_DICTIONARY_VALUE("User",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 15),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.datacontract.org/2004/07/EpicWareWeb.Models",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 16),
            WS_XML_STRING_DICTIONARY_VALUE("getUserFriendsByUserIdResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 17),
            WS_XML_STRING_DICTIONARY_VALUE("getUserByAutetication",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 18),
            WS_XML_STRING_DICTIONARY_VALUE("password",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 19),
            WS_XML_STRING_DICTIONARY_VALUE("getUserByAuteticationResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 20),
            WS_XML_STRING_DICTIONARY_VALUE("getUserByAuteticationResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 21),
            WS_XML_STRING_DICTIONARY_VALUE("GetEveryWord",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 22),
            WS_XML_STRING_DICTIONARY_VALUE("GetEveryWordResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 23),
            WS_XML_STRING_DICTIONARY_VALUE("Word",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 24),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.datacontract.org/2004/07/EpicWareWeb",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 25),
            WS_XML_STRING_DICTIONARY_VALUE("GetEveryWordResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 26),
            WS_XML_STRING_DICTIONARY_VALUE("getAllUsersID",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 27),
            WS_XML_STRING_DICTIONARY_VALUE("getAllUsersIDResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 28),
            WS_XML_STRING_DICTIONARY_VALUE("int",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 29),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.microsoft.com/2003/10/Serialization/Arrays",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 30),
            WS_XML_STRING_DICTIONARY_VALUE("getAllUsersIDResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 31),
            WS_XML_STRING_DICTIONARY_VALUE("getConnectioStrenght",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 32),
            WS_XML_STRING_DICTIONARY_VALUE("id1",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 33),
            WS_XML_STRING_DICTIONARY_VALUE("id2",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 34),
            WS_XML_STRING_DICTIONARY_VALUE("getConnectioStrenghtResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 35),
            WS_XML_STRING_DICTIONARY_VALUE("getConnectioStrenghtResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 36),
        },  // end of xmlStrings
        
        {  // tempuri_org_xsddictionary
          // abe6af18-04a7-4474-a73f-ebe2728697b0 
        { 0xabe6af18, 0x04a7, 0x4474, { 0xa7, 0x3f, 0xeb,0xe2, 0x72, 0x86, 0x97, 0xb0 } },
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings,
        37,
        TRUE,
        },
    },  //  end of dictionary
}; //  end of tempuri_org_xsdLocalDefinitions

const _tempuri_org_xsd tempuri_org_xsd =
{
    {  // globalElements
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeName, // getNumberUsers
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.getNumberUsers,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersResponseTypeName, // getNumberUsersResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.getNumberUsersResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberDownloadsTypeName, // getNumberDownloads
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.getNumberDownloads,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberDownloadsResponseTypeName, // getNumberDownloadsResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.getNumberDownloadsResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getUserByIDTypeName, // getUserByID
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.getUserByID,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getUserByIDResponseTypeName, // getUserByIDResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.getUserByIDResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getUserFriendsByUserIdTypeName, // getUserFriendsByUserId
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.getUserFriendsByUserId,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getUserFriendsByUserIdResponseTypeName, // getUserFriendsByUserIdResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.getUserFriendsByUserIdResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getUserByAuteticationTypeName, // getUserByAutetication
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.getUserByAutetication,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getUserByAuteticationResponseTypeName, // getUserByAuteticationResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.getUserByAuteticationResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetEveryWordTypeName, // GetEveryWord
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.GetEveryWord,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetEveryWordResponseTypeName, // GetEveryWordResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.GetEveryWordResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getAllUsersIDTypeName, // getAllUsersID
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.getAllUsersID,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getAllUsersIDResponseTypeName, // getAllUsersIDResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.getAllUsersIDResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getConnectioStrenghtTypeName, // getConnectioStrenght
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.getConnectioStrenght,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getConnectioStrenghtResponseTypeName, // getConnectioStrenghtResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.getConnectioStrenghtResponse,
        },
    },  // globalElements
    {  // begin of externallyReferencedTypes
        {
        0,
        1,
        0,
        0,
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeName, // getNumberUsers
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _getNumberUsers
        {
        sizeof(_getNumberUsersResponse),
        __alignof(_getNumberUsersResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._getNumberUsersResponsedescs._getNumberUsersResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._getNumberUsersResponsedescs._getNumberUsersResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersResponseTypeName, // getNumberUsersResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _getNumberUsersResponse
        {
        0,
        1,
        0,
        0,
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberDownloadsTypeName, // getNumberDownloads
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _getNumberDownloads
        {
        sizeof(_getNumberDownloadsResponse),
        __alignof(_getNumberDownloadsResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._getNumberDownloadsResponsedescs._getNumberDownloadsResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._getNumberDownloadsResponsedescs._getNumberDownloadsResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberDownloadsResponseTypeName, // getNumberDownloadsResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _getNumberDownloadsResponse
        {
        sizeof(_getUserByID),
        __alignof(_getUserByID),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._getUserByIDdescs._getUserByIDFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._getUserByIDdescs._getUserByIDFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getUserByIDTypeName, // getUserByID
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _getUserByID
        {
        sizeof(_getUserByIDResponse),
        __alignof(_getUserByIDResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._getUserByIDResponsedescs._getUserByIDResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._getUserByIDResponsedescs._getUserByIDResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getUserByIDResponseTypeName, // getUserByIDResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _getUserByIDResponse
        {
        sizeof(_getUserFriendsByUserId),
        __alignof(_getUserFriendsByUserId),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._getUserFriendsByUserIddescs._getUserFriendsByUserIdFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._getUserFriendsByUserIddescs._getUserFriendsByUserIdFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getUserFriendsByUserIdTypeName, // getUserFriendsByUserId
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _getUserFriendsByUserId
        {
        sizeof(_getUserFriendsByUserIdResponse),
        __alignof(_getUserFriendsByUserIdResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._getUserFriendsByUserIdResponsedescs._getUserFriendsByUserIdResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._getUserFriendsByUserIdResponsedescs._getUserFriendsByUserIdResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getUserFriendsByUserIdResponseTypeName, // getUserFriendsByUserIdResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _getUserFriendsByUserIdResponse
        {
        sizeof(_getUserByAutetication),
        __alignof(_getUserByAutetication),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._getUserByAuteticationdescs._getUserByAuteticationFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._getUserByAuteticationdescs._getUserByAuteticationFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getUserByAuteticationTypeName, // getUserByAutetication
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _getUserByAutetication
        {
        sizeof(_getUserByAuteticationResponse),
        __alignof(_getUserByAuteticationResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._getUserByAuteticationResponsedescs._getUserByAuteticationResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._getUserByAuteticationResponsedescs._getUserByAuteticationResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getUserByAuteticationResponseTypeName, // getUserByAuteticationResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _getUserByAuteticationResponse
        {
        0,
        1,
        0,
        0,
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetEveryWordTypeName, // GetEveryWord
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _GetEveryWord
        {
        sizeof(_GetEveryWordResponse),
        __alignof(_GetEveryWordResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._GetEveryWordResponsedescs._GetEveryWordResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._GetEveryWordResponsedescs._GetEveryWordResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetEveryWordResponseTypeName, // GetEveryWordResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _GetEveryWordResponse
        {
        0,
        1,
        0,
        0,
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getAllUsersIDTypeName, // getAllUsersID
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _getAllUsersID
        {
        sizeof(_getAllUsersIDResponse),
        __alignof(_getAllUsersIDResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._getAllUsersIDResponsedescs._getAllUsersIDResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._getAllUsersIDResponsedescs._getAllUsersIDResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getAllUsersIDResponseTypeName, // getAllUsersIDResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _getAllUsersIDResponse
        {
        sizeof(_getConnectioStrenght),
        __alignof(_getConnectioStrenght),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._getConnectioStrenghtdescs._getConnectioStrenghtFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._getConnectioStrenghtdescs._getConnectioStrenghtFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getConnectioStrenghtTypeName, // getConnectioStrenght
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _getConnectioStrenght
        {
        sizeof(_getConnectioStrenghtResponse),
        __alignof(_getConnectioStrenghtResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._getConnectioStrenghtResponsedescs._getConnectioStrenghtResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._getConnectioStrenghtResponsedescs._getConnectioStrenghtResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getConnectioStrenghtResponseTypeName, // getConnectioStrenghtResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getNumberUsersTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _getConnectioStrenghtResponse
    },  // end of externallyReferencedTypes;
}; // end of _tempuri_org_xsd
