
// File generated by Wsutil Compiler version 1.0095 
#include <WebServices.h>
#include "EpicWareWeb.Models.xsd.h"
#include "schemas.microsoft.com.2003.10.Serialization.Arrays.xsd.h"
#include "EpicWareWeb.xsd.h"
#include "tempuri.org.xsd.h"
#include "tempuri.org.wsdl.h"

typedef struct _tempuri_org_wsdlLocalDefinitions 
{
    struct  // messages
    {
        WS_MESSAGE_DESCRIPTION IWebService_getNumberUsers_InputMessage;
        WS_MESSAGE_DESCRIPTION IWebService_getNumberUsers_OutputMessage;
        WS_MESSAGE_DESCRIPTION IWebService_getNumberDownloads_InputMessage;
        WS_MESSAGE_DESCRIPTION IWebService_getNumberDownloads_OutputMessage;
        WS_MESSAGE_DESCRIPTION IWebService_getUserByID_InputMessage;
        WS_MESSAGE_DESCRIPTION IWebService_getUserByID_OutputMessage;
        WS_MESSAGE_DESCRIPTION IWebService_getUserFriendsByUserId_InputMessage;
        WS_MESSAGE_DESCRIPTION IWebService_getUserFriendsByUserId_OutputMessage;
        WS_MESSAGE_DESCRIPTION IWebService_getUserByAutetication_InputMessage;
        WS_MESSAGE_DESCRIPTION IWebService_getUserByAutetication_OutputMessage;
        WS_MESSAGE_DESCRIPTION IWebService_GetEveryWord_InputMessage;
        WS_MESSAGE_DESCRIPTION IWebService_GetEveryWord_OutputMessage;
        WS_MESSAGE_DESCRIPTION IWebService_getAllUsersID_InputMessage;
        WS_MESSAGE_DESCRIPTION IWebService_getAllUsersID_OutputMessage;
        WS_MESSAGE_DESCRIPTION IWebService_getConnectioStrenght_InputMessage;
        WS_MESSAGE_DESCRIPTION IWebService_getConnectioStrenght_OutputMessage;
        WS_MESSAGE_DESCRIPTION IWebService_getNumberTagsForUserId_InputMessage;
        WS_MESSAGE_DESCRIPTION IWebService_getNumberTagsForUserId_OutputMessage;
        WS_MESSAGE_DESCRIPTION IWebService_getStrenghtConnection_InputMessage;
        WS_MESSAGE_DESCRIPTION IWebService_getStrenghtConnection_OutputMessage;
        WS_MESSAGE_DESCRIPTION IWebService_getUserData_InputMessage;
        WS_MESSAGE_DESCRIPTION IWebService_getUserData_OutputMessage;
        WS_MESSAGE_DESCRIPTION IWebService_createFriendRequest_InputMessage;
        WS_MESSAGE_DESCRIPTION IWebService_createFriendRequest_OutputMessage;
    } messages;  // end of messages
    struct  // contracts
    {
        struct  // BasicHttpBinding_IWebService
        {
            struct  // BasicHttpBinding_IWebService_getNumberUsers
            {
                WS_PARAMETER_DESCRIPTION params[1];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IWebService_getNumberUsers;
            } BasicHttpBinding_IWebService_getNumberUsers;
            struct  // BasicHttpBinding_IWebService_getNumberDownloads
            {
                WS_PARAMETER_DESCRIPTION params[1];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IWebService_getNumberDownloads;
            } BasicHttpBinding_IWebService_getNumberDownloads;
            struct  // BasicHttpBinding_IWebService_getUserByID
            {
                WS_PARAMETER_DESCRIPTION params[4];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IWebService_getUserByID;
            } BasicHttpBinding_IWebService_getUserByID;
            struct  // BasicHttpBinding_IWebService_getUserFriendsByUserId
            {
                WS_PARAMETER_DESCRIPTION params[5];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IWebService_getUserFriendsByUserId;
            } BasicHttpBinding_IWebService_getUserFriendsByUserId;
            struct  // BasicHttpBinding_IWebService_getUserByAutetication
            {
                WS_PARAMETER_DESCRIPTION params[3];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IWebService_getUserByAutetication;
            } BasicHttpBinding_IWebService_getUserByAutetication;
            struct  // BasicHttpBinding_IWebService_GetEveryWord
            {
                WS_PARAMETER_DESCRIPTION params[2];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IWebService_GetEveryWord;
            } BasicHttpBinding_IWebService_GetEveryWord;
            struct  // BasicHttpBinding_IWebService_getAllUsersID
            {
                WS_PARAMETER_DESCRIPTION params[2];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IWebService_getAllUsersID;
            } BasicHttpBinding_IWebService_getAllUsersID;
            struct  // BasicHttpBinding_IWebService_getConnectioStrenght
            {
                WS_PARAMETER_DESCRIPTION params[3];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IWebService_getConnectioStrenght;
            } BasicHttpBinding_IWebService_getConnectioStrenght;
            struct  // BasicHttpBinding_IWebService_getNumberTagsForUserId
            {
                WS_PARAMETER_DESCRIPTION params[4];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IWebService_getNumberTagsForUserId;
            } BasicHttpBinding_IWebService_getNumberTagsForUserId;
            struct  // BasicHttpBinding_IWebService_getStrenghtConnection
            {
                WS_PARAMETER_DESCRIPTION params[5];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IWebService_getStrenghtConnection;
            } BasicHttpBinding_IWebService_getStrenghtConnection;
            struct  // BasicHttpBinding_IWebService_getUserData
            {
                WS_PARAMETER_DESCRIPTION params[4];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IWebService_getUserData;
            } BasicHttpBinding_IWebService_getUserData;
            struct  // BasicHttpBinding_IWebService_createFriendRequest
            {
                WS_PARAMETER_DESCRIPTION params[5];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IWebService_createFriendRequest;
            } BasicHttpBinding_IWebService_createFriendRequest;
            WS_OPERATION_DESCRIPTION* operations[12];
            WS_CONTRACT_DESCRIPTION contractDesc;
        } BasicHttpBinding_IWebService;
    } contracts;  // endof contracts 
    struct  // policies
    {
        struct  // BasicHttpBinding_IWebService
        {
            WS_ENCODING encoding;
            WS_ADDRESSING_VERSION addressingVersion;
            WS_ENVELOPE_VERSION envelopeVersion;
            WS_CHANNEL_PROPERTY channelPropertiesArray[3];
        } BasicHttpBinding_IWebService;
    } policies;
    struct  // XML dictionary
    {
        struct  // XML string list
        {
            WS_XML_STRING IWebService_getNumberUsers_InputMessageactionName;  // http://tempuri.org/IWebService/getNumberUsers
            WS_XML_STRING IWebService_getNumberUsers_OutputMessageactionName;  // http://tempuri.org/IWebService/getNumberUsersResponse
            WS_XML_STRING IWebService_getNumberDownloads_InputMessageactionName;  // http://tempuri.org/IWebService/getNumberDownloads
            WS_XML_STRING IWebService_getNumberDownloads_OutputMessageactionName;  // http://tempuri.org/IWebService/getNumberDownloadsResponse
            WS_XML_STRING IWebService_getUserByID_InputMessageactionName;  // http://tempuri.org/IWebService/getUserByID
            WS_XML_STRING IWebService_getUserByID_OutputMessageactionName;  // http://tempuri.org/IWebService/getUserByIDResponse
            WS_XML_STRING IWebService_getUserFriendsByUserId_InputMessageactionName;  // http://tempuri.org/IWebService/getUserFriendsByUserId
            WS_XML_STRING IWebService_getUserFriendsByUserId_OutputMessageactionName;  // http://tempuri.org/IWebService/getUserFriendsByUserIdResponse
            WS_XML_STRING IWebService_getUserByAutetication_InputMessageactionName;  // http://tempuri.org/IWebService/getUserByAutetication
            WS_XML_STRING IWebService_getUserByAutetication_OutputMessageactionName;  // http://tempuri.org/IWebService/getUserByAuteticationResponse
            WS_XML_STRING IWebService_GetEveryWord_InputMessageactionName;  // http://tempuri.org/IWebService/GetEveryWord
            WS_XML_STRING IWebService_GetEveryWord_OutputMessageactionName;  // http://tempuri.org/IWebService/GetEveryWordResponse
            WS_XML_STRING IWebService_getAllUsersID_InputMessageactionName;  // http://tempuri.org/IWebService/getAllUsersID
            WS_XML_STRING IWebService_getAllUsersID_OutputMessageactionName;  // http://tempuri.org/IWebService/getAllUsersIDResponse
            WS_XML_STRING IWebService_getConnectioStrenght_InputMessageactionName;  // http://tempuri.org/IWebService/getConnectioStrenght
            WS_XML_STRING IWebService_getConnectioStrenght_OutputMessageactionName;  // http://tempuri.org/IWebService/getConnectioStrenghtResponse
            WS_XML_STRING IWebService_getNumberTagsForUserId_InputMessageactionName;  // http://tempuri.org/IWebService/getNumberTagsForUserId
            WS_XML_STRING IWebService_getNumberTagsForUserId_OutputMessageactionName;  // http://tempuri.org/IWebService/getNumberTagsForUserIdResponse
            WS_XML_STRING IWebService_getStrenghtConnection_InputMessageactionName;  // http://tempuri.org/IWebService/getStrenghtConnection
            WS_XML_STRING IWebService_getStrenghtConnection_OutputMessageactionName;  // http://tempuri.org/IWebService/getStrenghtConnectionResponse
            WS_XML_STRING IWebService_getUserData_InputMessageactionName;  // http://tempuri.org/IWebService/getUserData
            WS_XML_STRING IWebService_getUserData_OutputMessageactionName;  // http://tempuri.org/IWebService/getUserDataResponse
            WS_XML_STRING IWebService_createFriendRequest_InputMessageactionName;  // http://tempuri.org/IWebService/createFriendRequest
            WS_XML_STRING IWebService_createFriendRequest_OutputMessageactionName;  // http://tempuri.org/IWebService/createFriendRequestResponse
        } xmlStrings;  // end of XML string list
        WS_XML_DICTIONARY dict;
    } dictionary;  // end of XML dictionary
} _tempuri_org_wsdlLocalDefinitions;


typedef struct BasicHttpBinding_IWebService_getNumberUsersParamStruct 
{
    int* getNumberUsersResult;
} BasicHttpBinding_IWebService_getNumberUsersParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IWebService_getNumberUsersOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IWebService_getNumberUsersCallback _operation = (BasicHttpBinding_IWebService_getNumberUsersCallback)_callback;
    BasicHttpBinding_IWebService_getNumberUsersParamStruct *_stack =(BasicHttpBinding_IWebService_getNumberUsersParamStruct*)_stackStruct;
    return _operation( 
        _context,
        (_stack->getNumberUsersResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IWebService_getNumberDownloadsParamStruct 
{
    int* getNumberDownloadsResult;
} BasicHttpBinding_IWebService_getNumberDownloadsParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IWebService_getNumberDownloadsOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IWebService_getNumberDownloadsCallback _operation = (BasicHttpBinding_IWebService_getNumberDownloadsCallback)_callback;
    BasicHttpBinding_IWebService_getNumberDownloadsParamStruct *_stack =(BasicHttpBinding_IWebService_getNumberDownloadsParamStruct*)_stackStruct;
    return _operation( 
        _context,
        (_stack->getNumberDownloadsResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IWebService_getUserByIDParamStruct 
{
    int* id;
    WCHAR** user;
    WCHAR** pass;
    User** getUserByIDResult;
} BasicHttpBinding_IWebService_getUserByIDParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IWebService_getUserByIDOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IWebService_getUserByIDCallback _operation = (BasicHttpBinding_IWebService_getUserByIDCallback)_callback;
    BasicHttpBinding_IWebService_getUserByIDParamStruct *_stack =(BasicHttpBinding_IWebService_getUserByIDParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->id),
        *(_stack->user),
        *(_stack->pass),
        (_stack->getUserByIDResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IWebService_getUserFriendsByUserIdParamStruct 
{
    int* id;
    WCHAR** user;
    WCHAR** pass;
    unsigned int* getUserFriendsByUserIdResultCount;
    int** getUserFriendsByUserIdResult;
} BasicHttpBinding_IWebService_getUserFriendsByUserIdParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IWebService_getUserFriendsByUserIdOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IWebService_getUserFriendsByUserIdCallback _operation = (BasicHttpBinding_IWebService_getUserFriendsByUserIdCallback)_callback;
    BasicHttpBinding_IWebService_getUserFriendsByUserIdParamStruct *_stack =(BasicHttpBinding_IWebService_getUserFriendsByUserIdParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->id),
        *(_stack->user),
        *(_stack->pass),
        _stack->getUserFriendsByUserIdResultCount,
        (_stack->getUserFriendsByUserIdResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IWebService_getUserByAuteticationParamStruct 
{
    WCHAR** user;
    WCHAR** password;
    User** getUserByAuteticationResult;
} BasicHttpBinding_IWebService_getUserByAuteticationParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IWebService_getUserByAuteticationOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IWebService_getUserByAuteticationCallback _operation = (BasicHttpBinding_IWebService_getUserByAuteticationCallback)_callback;
    BasicHttpBinding_IWebService_getUserByAuteticationParamStruct *_stack =(BasicHttpBinding_IWebService_getUserByAuteticationParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->user),
        *(_stack->password),
        (_stack->getUserByAuteticationResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IWebService_GetEveryWordParamStruct 
{
    unsigned int* GetEveryWordResultCount;
    Word** GetEveryWordResult;
} BasicHttpBinding_IWebService_GetEveryWordParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IWebService_GetEveryWordOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IWebService_GetEveryWordCallback _operation = (BasicHttpBinding_IWebService_GetEveryWordCallback)_callback;
    BasicHttpBinding_IWebService_GetEveryWordParamStruct *_stack =(BasicHttpBinding_IWebService_GetEveryWordParamStruct*)_stackStruct;
    return _operation( 
        _context,
        _stack->GetEveryWordResultCount,
        (_stack->GetEveryWordResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IWebService_getAllUsersIDParamStruct 
{
    unsigned int* getAllUsersIDResultCount;
    int** getAllUsersIDResult;
} BasicHttpBinding_IWebService_getAllUsersIDParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IWebService_getAllUsersIDOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IWebService_getAllUsersIDCallback _operation = (BasicHttpBinding_IWebService_getAllUsersIDCallback)_callback;
    BasicHttpBinding_IWebService_getAllUsersIDParamStruct *_stack =(BasicHttpBinding_IWebService_getAllUsersIDParamStruct*)_stackStruct;
    return _operation( 
        _context,
        _stack->getAllUsersIDResultCount,
        (_stack->getAllUsersIDResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IWebService_getConnectioStrenghtParamStruct 
{
    int* id1;
    int* id2;
    int* getConnectioStrenghtResult;
} BasicHttpBinding_IWebService_getConnectioStrenghtParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IWebService_getConnectioStrenghtOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IWebService_getConnectioStrenghtCallback _operation = (BasicHttpBinding_IWebService_getConnectioStrenghtCallback)_callback;
    BasicHttpBinding_IWebService_getConnectioStrenghtParamStruct *_stack =(BasicHttpBinding_IWebService_getConnectioStrenghtParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->id1),
        *(_stack->id2),
        (_stack->getConnectioStrenghtResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IWebService_getNumberTagsForUserIdParamStruct 
{
    int* id;
    WCHAR** user;
    WCHAR** pass;
    int* getNumberTagsForUserIdResult;
} BasicHttpBinding_IWebService_getNumberTagsForUserIdParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IWebService_getNumberTagsForUserIdOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IWebService_getNumberTagsForUserIdCallback _operation = (BasicHttpBinding_IWebService_getNumberTagsForUserIdCallback)_callback;
    BasicHttpBinding_IWebService_getNumberTagsForUserIdParamStruct *_stack =(BasicHttpBinding_IWebService_getNumberTagsForUserIdParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->id),
        *(_stack->user),
        *(_stack->pass),
        (_stack->getNumberTagsForUserIdResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IWebService_getStrenghtConnectionParamStruct 
{
    int* id1;
    int* id2;
    WCHAR** user;
    WCHAR** pass;
    int* getStrenghtConnectionResult;
} BasicHttpBinding_IWebService_getStrenghtConnectionParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IWebService_getStrenghtConnectionOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IWebService_getStrenghtConnectionCallback _operation = (BasicHttpBinding_IWebService_getStrenghtConnectionCallback)_callback;
    BasicHttpBinding_IWebService_getStrenghtConnectionParamStruct *_stack =(BasicHttpBinding_IWebService_getStrenghtConnectionParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->id1),
        *(_stack->id2),
        *(_stack->user),
        *(_stack->pass),
        (_stack->getStrenghtConnectionResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IWebService_getUserDataParamStruct 
{
    int* id;
    WCHAR** user;
    WCHAR** pass;
    UserData** getUserDataResult;
} BasicHttpBinding_IWebService_getUserDataParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IWebService_getUserDataOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IWebService_getUserDataCallback _operation = (BasicHttpBinding_IWebService_getUserDataCallback)_callback;
    BasicHttpBinding_IWebService_getUserDataParamStruct *_stack =(BasicHttpBinding_IWebService_getUserDataParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->id),
        *(_stack->user),
        *(_stack->pass),
        (_stack->getUserDataResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IWebService_createFriendRequestParamStruct 
{
    int* id1;
    int* id2;
    WCHAR** user;
    WCHAR** pass;
    BOOL* createFriendRequestResult;
} BasicHttpBinding_IWebService_createFriendRequestParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IWebService_createFriendRequestOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IWebService_createFriendRequestCallback _operation = (BasicHttpBinding_IWebService_createFriendRequestCallback)_callback;
    BasicHttpBinding_IWebService_createFriendRequestParamStruct *_stack =(BasicHttpBinding_IWebService_createFriendRequestParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->id1),
        *(_stack->id2),
        *(_stack->user),
        *(_stack->pass),
        (_stack->createFriendRequestResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif
const static _tempuri_org_wsdlLocalDefinitions tempuri_org_wsdlLocalDefinitions =
{
    {  // messages
        {  // message description for IWebService_getNumberUsers_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getNumberUsers_InputMessageactionName, // http://tempuri.org/IWebService/getNumberUsers
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getNumberUsers, 
        },    // message description for IWebService_getNumberUsers_InputMessage
        {  // message description for IWebService_getNumberUsers_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getNumberUsers_OutputMessageactionName, // http://tempuri.org/IWebService/getNumberUsersResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getNumberUsersResponse, 
        },    // message description for IWebService_getNumberUsers_OutputMessage
        {  // message description for IWebService_getNumberDownloads_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getNumberDownloads_InputMessageactionName, // http://tempuri.org/IWebService/getNumberDownloads
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getNumberDownloads, 
        },    // message description for IWebService_getNumberDownloads_InputMessage
        {  // message description for IWebService_getNumberDownloads_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getNumberDownloads_OutputMessageactionName, // http://tempuri.org/IWebService/getNumberDownloadsResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getNumberDownloadsResponse, 
        },    // message description for IWebService_getNumberDownloads_OutputMessage
        {  // message description for IWebService_getUserByID_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getUserByID_InputMessageactionName, // http://tempuri.org/IWebService/getUserByID
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getUserByID, 
        },    // message description for IWebService_getUserByID_InputMessage
        {  // message description for IWebService_getUserByID_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getUserByID_OutputMessageactionName, // http://tempuri.org/IWebService/getUserByIDResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getUserByIDResponse, 
        },    // message description for IWebService_getUserByID_OutputMessage
        {  // message description for IWebService_getUserFriendsByUserId_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getUserFriendsByUserId_InputMessageactionName, // http://tempuri.org/IWebService/getUserFriendsByUserId
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getUserFriendsByUserId, 
        },    // message description for IWebService_getUserFriendsByUserId_InputMessage
        {  // message description for IWebService_getUserFriendsByUserId_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getUserFriendsByUserId_OutputMessageactionName, // http://tempuri.org/IWebService/getUserFriendsByUserIdResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getUserFriendsByUserIdResponse, 
        },    // message description for IWebService_getUserFriendsByUserId_OutputMessage
        {  // message description for IWebService_getUserByAutetication_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getUserByAutetication_InputMessageactionName, // http://tempuri.org/IWebService/getUserByAutetication
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getUserByAutetication, 
        },    // message description for IWebService_getUserByAutetication_InputMessage
        {  // message description for IWebService_getUserByAutetication_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getUserByAutetication_OutputMessageactionName, // http://tempuri.org/IWebService/getUserByAuteticationResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getUserByAuteticationResponse, 
        },    // message description for IWebService_getUserByAutetication_OutputMessage
        {  // message description for IWebService_GetEveryWord_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_GetEveryWord_InputMessageactionName, // http://tempuri.org/IWebService/GetEveryWord
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.GetEveryWord, 
        },    // message description for IWebService_GetEveryWord_InputMessage
        {  // message description for IWebService_GetEveryWord_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_GetEveryWord_OutputMessageactionName, // http://tempuri.org/IWebService/GetEveryWordResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.GetEveryWordResponse, 
        },    // message description for IWebService_GetEveryWord_OutputMessage
        {  // message description for IWebService_getAllUsersID_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getAllUsersID_InputMessageactionName, // http://tempuri.org/IWebService/getAllUsersID
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getAllUsersID, 
        },    // message description for IWebService_getAllUsersID_InputMessage
        {  // message description for IWebService_getAllUsersID_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getAllUsersID_OutputMessageactionName, // http://tempuri.org/IWebService/getAllUsersIDResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getAllUsersIDResponse, 
        },    // message description for IWebService_getAllUsersID_OutputMessage
        {  // message description for IWebService_getConnectioStrenght_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getConnectioStrenght_InputMessageactionName, // http://tempuri.org/IWebService/getConnectioStrenght
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getConnectioStrenght, 
        },    // message description for IWebService_getConnectioStrenght_InputMessage
        {  // message description for IWebService_getConnectioStrenght_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getConnectioStrenght_OutputMessageactionName, // http://tempuri.org/IWebService/getConnectioStrenghtResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getConnectioStrenghtResponse, 
        },    // message description for IWebService_getConnectioStrenght_OutputMessage
        {  // message description for IWebService_getNumberTagsForUserId_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getNumberTagsForUserId_InputMessageactionName, // http://tempuri.org/IWebService/getNumberTagsForUserId
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getNumberTagsForUserId, 
        },    // message description for IWebService_getNumberTagsForUserId_InputMessage
        {  // message description for IWebService_getNumberTagsForUserId_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getNumberTagsForUserId_OutputMessageactionName, // http://tempuri.org/IWebService/getNumberTagsForUserIdResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getNumberTagsForUserIdResponse, 
        },    // message description for IWebService_getNumberTagsForUserId_OutputMessage
        {  // message description for IWebService_getStrenghtConnection_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getStrenghtConnection_InputMessageactionName, // http://tempuri.org/IWebService/getStrenghtConnection
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getStrenghtConnection, 
        },    // message description for IWebService_getStrenghtConnection_InputMessage
        {  // message description for IWebService_getStrenghtConnection_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getStrenghtConnection_OutputMessageactionName, // http://tempuri.org/IWebService/getStrenghtConnectionResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getStrenghtConnectionResponse, 
        },    // message description for IWebService_getStrenghtConnection_OutputMessage
        {  // message description for IWebService_getUserData_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getUserData_InputMessageactionName, // http://tempuri.org/IWebService/getUserData
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getUserData, 
        },    // message description for IWebService_getUserData_InputMessage
        {  // message description for IWebService_getUserData_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getUserData_OutputMessageactionName, // http://tempuri.org/IWebService/getUserDataResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getUserDataResponse, 
        },    // message description for IWebService_getUserData_OutputMessage
        {  // message description for IWebService_createFriendRequest_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_createFriendRequest_InputMessageactionName, // http://tempuri.org/IWebService/createFriendRequest
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.createFriendRequest, 
        },    // message description for IWebService_createFriendRequest_InputMessage
        {  // message description for IWebService_createFriendRequest_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_createFriendRequest_OutputMessageactionName, // http://tempuri.org/IWebService/createFriendRequestResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.createFriendRequestResponse, 
        },    // message description for IWebService_createFriendRequest_OutputMessage
    },  // end of messages 
    {  // contracts
        {  // BasicHttpBinding_IWebService,
            {  // BasicHttpBinding_IWebService_getNumberUsers
                {  // parameter descriptions for BasicHttpBinding_IWebService_getNumberUsers
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IWebService_getNumberUsers
                {  // operation description for BasicHttpBinding_IWebService_getNumberUsers
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IWebService_getNumberUsers_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IWebService_getNumberUsers_OutputMessage, 
                    0,
                    0,
                    1,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getNumberUsers.params,
                    BasicHttpBinding_IWebService_getNumberUsersOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IWebService_getNumberUsers
            },  // BasicHttpBinding_IWebService_getNumberUsers
            {  // BasicHttpBinding_IWebService_getNumberDownloads
                {  // parameter descriptions for BasicHttpBinding_IWebService_getNumberDownloads
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IWebService_getNumberDownloads
                {  // operation description for BasicHttpBinding_IWebService_getNumberDownloads
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IWebService_getNumberDownloads_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IWebService_getNumberDownloads_OutputMessage, 
                    0,
                    0,
                    1,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getNumberDownloads.params,
                    BasicHttpBinding_IWebService_getNumberDownloadsOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IWebService_getNumberDownloads
            },  // BasicHttpBinding_IWebService_getNumberDownloads
            {  // BasicHttpBinding_IWebService_getUserByID
                {  // parameter descriptions for BasicHttpBinding_IWebService_getUserByID
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)2, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IWebService_getUserByID
                {  // operation description for BasicHttpBinding_IWebService_getUserByID
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IWebService_getUserByID_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IWebService_getUserByID_OutputMessage, 
                    0,
                    0,
                    4,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getUserByID.params,
                    BasicHttpBinding_IWebService_getUserByIDOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IWebService_getUserByID
            },  // BasicHttpBinding_IWebService_getUserByID
            {  // BasicHttpBinding_IWebService_getUserFriendsByUserId
                {  // parameter descriptions for BasicHttpBinding_IWebService_getUserFriendsByUserId
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)2, (USHORT)-1},
                    {WS_PARAMETER_TYPE_ARRAY_COUNT, (USHORT)-1, (USHORT)0},
                    {WS_PARAMETER_TYPE_ARRAY, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IWebService_getUserFriendsByUserId
                {  // operation description for BasicHttpBinding_IWebService_getUserFriendsByUserId
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IWebService_getUserFriendsByUserId_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IWebService_getUserFriendsByUserId_OutputMessage, 
                    0,
                    0,
                    5,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getUserFriendsByUserId.params,
                    BasicHttpBinding_IWebService_getUserFriendsByUserIdOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IWebService_getUserFriendsByUserId
            },  // BasicHttpBinding_IWebService_getUserFriendsByUserId
            {  // BasicHttpBinding_IWebService_getUserByAutetication
                {  // parameter descriptions for BasicHttpBinding_IWebService_getUserByAutetication
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IWebService_getUserByAutetication
                {  // operation description for BasicHttpBinding_IWebService_getUserByAutetication
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IWebService_getUserByAutetication_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IWebService_getUserByAutetication_OutputMessage, 
                    0,
                    0,
                    3,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getUserByAutetication.params,
                    BasicHttpBinding_IWebService_getUserByAuteticationOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IWebService_getUserByAutetication
            },  // BasicHttpBinding_IWebService_getUserByAutetication
            {  // BasicHttpBinding_IWebService_GetEveryWord
                {  // parameter descriptions for BasicHttpBinding_IWebService_GetEveryWord
                    {WS_PARAMETER_TYPE_ARRAY_COUNT, (USHORT)-1, (USHORT)0},
                    {WS_PARAMETER_TYPE_ARRAY, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IWebService_GetEveryWord
                {  // operation description for BasicHttpBinding_IWebService_GetEveryWord
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IWebService_GetEveryWord_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IWebService_GetEveryWord_OutputMessage, 
                    0,
                    0,
                    2,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_GetEveryWord.params,
                    BasicHttpBinding_IWebService_GetEveryWordOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IWebService_GetEveryWord
            },  // BasicHttpBinding_IWebService_GetEveryWord
            {  // BasicHttpBinding_IWebService_getAllUsersID
                {  // parameter descriptions for BasicHttpBinding_IWebService_getAllUsersID
                    {WS_PARAMETER_TYPE_ARRAY_COUNT, (USHORT)-1, (USHORT)0},
                    {WS_PARAMETER_TYPE_ARRAY, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IWebService_getAllUsersID
                {  // operation description for BasicHttpBinding_IWebService_getAllUsersID
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IWebService_getAllUsersID_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IWebService_getAllUsersID_OutputMessage, 
                    0,
                    0,
                    2,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getAllUsersID.params,
                    BasicHttpBinding_IWebService_getAllUsersIDOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IWebService_getAllUsersID
            },  // BasicHttpBinding_IWebService_getAllUsersID
            {  // BasicHttpBinding_IWebService_getConnectioStrenght
                {  // parameter descriptions for BasicHttpBinding_IWebService_getConnectioStrenght
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IWebService_getConnectioStrenght
                {  // operation description for BasicHttpBinding_IWebService_getConnectioStrenght
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IWebService_getConnectioStrenght_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IWebService_getConnectioStrenght_OutputMessage, 
                    0,
                    0,
                    3,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getConnectioStrenght.params,
                    BasicHttpBinding_IWebService_getConnectioStrenghtOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IWebService_getConnectioStrenght
            },  // BasicHttpBinding_IWebService_getConnectioStrenght
            {  // BasicHttpBinding_IWebService_getNumberTagsForUserId
                {  // parameter descriptions for BasicHttpBinding_IWebService_getNumberTagsForUserId
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)2, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IWebService_getNumberTagsForUserId
                {  // operation description for BasicHttpBinding_IWebService_getNumberTagsForUserId
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IWebService_getNumberTagsForUserId_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IWebService_getNumberTagsForUserId_OutputMessage, 
                    0,
                    0,
                    4,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getNumberTagsForUserId.params,
                    BasicHttpBinding_IWebService_getNumberTagsForUserIdOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IWebService_getNumberTagsForUserId
            },  // BasicHttpBinding_IWebService_getNumberTagsForUserId
            {  // BasicHttpBinding_IWebService_getStrenghtConnection
                {  // parameter descriptions for BasicHttpBinding_IWebService_getStrenghtConnection
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)2, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)3, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IWebService_getStrenghtConnection
                {  // operation description for BasicHttpBinding_IWebService_getStrenghtConnection
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IWebService_getStrenghtConnection_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IWebService_getStrenghtConnection_OutputMessage, 
                    0,
                    0,
                    5,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getStrenghtConnection.params,
                    BasicHttpBinding_IWebService_getStrenghtConnectionOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IWebService_getStrenghtConnection
            },  // BasicHttpBinding_IWebService_getStrenghtConnection
            {  // BasicHttpBinding_IWebService_getUserData
                {  // parameter descriptions for BasicHttpBinding_IWebService_getUserData
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)2, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IWebService_getUserData
                {  // operation description for BasicHttpBinding_IWebService_getUserData
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IWebService_getUserData_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IWebService_getUserData_OutputMessage, 
                    0,
                    0,
                    4,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getUserData.params,
                    BasicHttpBinding_IWebService_getUserDataOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IWebService_getUserData
            },  // BasicHttpBinding_IWebService_getUserData
            {  // BasicHttpBinding_IWebService_createFriendRequest
                {  // parameter descriptions for BasicHttpBinding_IWebService_createFriendRequest
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)2, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)3, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IWebService_createFriendRequest
                {  // operation description for BasicHttpBinding_IWebService_createFriendRequest
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IWebService_createFriendRequest_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IWebService_createFriendRequest_OutputMessage, 
                    0,
                    0,
                    5,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_createFriendRequest.params,
                    BasicHttpBinding_IWebService_createFriendRequestOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IWebService_createFriendRequest
            },  // BasicHttpBinding_IWebService_createFriendRequest
            {  // array of operations for BasicHttpBinding_IWebService
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getNumberUsers.BasicHttpBinding_IWebService_getNumberUsers,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getNumberDownloads.BasicHttpBinding_IWebService_getNumberDownloads,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getUserByID.BasicHttpBinding_IWebService_getUserByID,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getUserFriendsByUserId.BasicHttpBinding_IWebService_getUserFriendsByUserId,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getUserByAutetication.BasicHttpBinding_IWebService_getUserByAutetication,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_GetEveryWord.BasicHttpBinding_IWebService_GetEveryWord,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getAllUsersID.BasicHttpBinding_IWebService_getAllUsersID,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getConnectioStrenght.BasicHttpBinding_IWebService_getConnectioStrenght,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getNumberTagsForUserId.BasicHttpBinding_IWebService_getNumberTagsForUserId,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getStrenghtConnection.BasicHttpBinding_IWebService_getStrenghtConnection,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getUserData.BasicHttpBinding_IWebService_getUserData,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_createFriendRequest.BasicHttpBinding_IWebService_createFriendRequest,
            },  // array of operations for BasicHttpBinding_IWebService
            {  // contract description for BasicHttpBinding_IWebService
            12,
            (WS_OPERATION_DESCRIPTION**)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.operations,
            },  // end of contract description for BasicHttpBinding_IWebService
        },  // BasicHttpBinding_IWebService
    },  // end of contracts 
    {  // policies
        {
            WS_ENCODING_XML_UTF8,
            WS_ADDRESSING_VERSION_TRANSPORT,
            WS_ENVELOPE_VERSION_SOAP_1_1,
            { // channelPropertiesArray
                {
                    WS_CHANNEL_PROPERTY_ENCODING,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IWebService.encoding,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IWebService.encoding),
                },
                {
                    WS_CHANNEL_PROPERTY_ADDRESSING_VERSION,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IWebService.addressingVersion,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IWebService.addressingVersion),
                },
                {
                    WS_CHANNEL_PROPERTY_ENVELOPE_VERSION,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IWebService.envelopeVersion,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IWebService.envelopeVersion),
                },
            },
        },   // end of BasicHttpBinding_IWebService,
    }, // policies
    {  // dictionary 
        {  // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IWebService/getNumberUsers",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IWebService/getNumberUsersResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IWebService/getNumberDownloads",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IWebService/getNumberDownloadsResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IWebService/getUserByID",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IWebService/getUserByIDResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IWebService/getUserFriendsByUserId",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IWebService/getUserFriendsByUserIdResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 7),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IWebService/getUserByAutetication",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 8),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IWebService/getUserByAuteticationResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 9),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IWebService/GetEveryWord",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 10),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IWebService/GetEveryWordResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 11),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IWebService/getAllUsersID",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 12),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IWebService/getAllUsersIDResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 13),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IWebService/getConnectioStrenght",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 14),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IWebService/getConnectioStrenghtResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 15),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IWebService/getNumberTagsForUserId",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 16),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IWebService/getNumberTagsForUserIdResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 17),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IWebService/getStrenghtConnection",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 18),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IWebService/getStrenghtConnectionResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 19),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IWebService/getUserData",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 20),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IWebService/getUserDataResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 21),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IWebService/createFriendRequest",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 22),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IWebService/createFriendRequestResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 23),
        },  // end of xmlStrings
        
        {  // tempuri_org_wsdldictionary
          // 1ed68632-925f-488f-a12c-fd26b837428f 
        { 0x1ed68632, 0x925f, 0x488f, { 0xa1, 0x2c, 0xfd,0x26, 0xb8, 0x37, 0x42, 0x8f } },
        (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings,
        24,
        TRUE,
        },
    },  //  end of dictionary
}; //  end of tempuri_org_wsdlLocalDefinitions

// Disable prefast warnings for the output parameters as their contract cannot be expressed in SAL.
#if (_MSC_VER >= 1400)
#pragma warning(push)
#endif
#pragma warning(disable: 6101 6054)

// operation: BasicHttpBinding_IWebService_getNumberUsers
HRESULT WINAPI BasicHttpBinding_IWebService_getNumberUsers(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _Out_ int* getNumberUsersResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[1]; 
    _argList[0] = &getNumberUsersResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getNumberUsers.BasicHttpBinding_IWebService_getNumberUsers,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IWebService_getNumberDownloads
HRESULT WINAPI BasicHttpBinding_IWebService_getNumberDownloads(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _Out_ int* getNumberDownloadsResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[1]; 
    _argList[0] = &getNumberDownloadsResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getNumberDownloads.BasicHttpBinding_IWebService_getNumberDownloads,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IWebService_getUserByID
HRESULT WINAPI BasicHttpBinding_IWebService_getUserByID(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_ int id, 
    _In_opt_z_ WCHAR* user, 
    _In_opt_z_ WCHAR* pass, 
    _Outptr_opt_ User** getUserByIDResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[4]; 
    _argList[0] = &id;
    _argList[1] = &user;
    _argList[2] = &pass;
    _argList[3] = &getUserByIDResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getUserByID.BasicHttpBinding_IWebService_getUserByID,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IWebService_getUserFriendsByUserId
HRESULT WINAPI BasicHttpBinding_IWebService_getUserFriendsByUserId(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_ int id, 
    _In_opt_z_ WCHAR* user, 
    _In_opt_z_ WCHAR* pass, 
    _Out_ unsigned int* getUserFriendsByUserIdResultCount, 
    _Outptr_opt_result_buffer_(*getUserFriendsByUserIdResultCount) int** getUserFriendsByUserIdResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[5]; 
    _argList[0] = &id;
    _argList[1] = &user;
    _argList[2] = &pass;
    _argList[3] = &getUserFriendsByUserIdResultCount;
    _argList[4] = &getUserFriendsByUserIdResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getUserFriendsByUserId.BasicHttpBinding_IWebService_getUserFriendsByUserId,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IWebService_getUserByAutetication
HRESULT WINAPI BasicHttpBinding_IWebService_getUserByAutetication(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_opt_z_ WCHAR* user, 
    _In_opt_z_ WCHAR* password, 
    _Outptr_opt_ User** getUserByAuteticationResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[3]; 
    _argList[0] = &user;
    _argList[1] = &password;
    _argList[2] = &getUserByAuteticationResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getUserByAutetication.BasicHttpBinding_IWebService_getUserByAutetication,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IWebService_GetEveryWord
HRESULT WINAPI BasicHttpBinding_IWebService_GetEveryWord(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _Out_ unsigned int* GetEveryWordResultCount, 
    _Outptr_opt_result_buffer_(*GetEveryWordResultCount) Word** GetEveryWordResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[2]; 
    _argList[0] = &GetEveryWordResultCount;
    _argList[1] = &GetEveryWordResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_GetEveryWord.BasicHttpBinding_IWebService_GetEveryWord,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IWebService_getAllUsersID
HRESULT WINAPI BasicHttpBinding_IWebService_getAllUsersID(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _Out_ unsigned int* getAllUsersIDResultCount, 
    _Outptr_opt_result_buffer_(*getAllUsersIDResultCount) int** getAllUsersIDResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[2]; 
    _argList[0] = &getAllUsersIDResultCount;
    _argList[1] = &getAllUsersIDResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getAllUsersID.BasicHttpBinding_IWebService_getAllUsersID,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IWebService_getConnectioStrenght
HRESULT WINAPI BasicHttpBinding_IWebService_getConnectioStrenght(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_ int id1, 
    _In_ int id2, 
    _Out_ int* getConnectioStrenghtResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[3]; 
    _argList[0] = &id1;
    _argList[1] = &id2;
    _argList[2] = &getConnectioStrenghtResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getConnectioStrenght.BasicHttpBinding_IWebService_getConnectioStrenght,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IWebService_getNumberTagsForUserId
HRESULT WINAPI BasicHttpBinding_IWebService_getNumberTagsForUserId(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_ int id, 
    _In_opt_z_ WCHAR* user, 
    _In_opt_z_ WCHAR* pass, 
    _Out_ int* getNumberTagsForUserIdResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[4]; 
    _argList[0] = &id;
    _argList[1] = &user;
    _argList[2] = &pass;
    _argList[3] = &getNumberTagsForUserIdResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getNumberTagsForUserId.BasicHttpBinding_IWebService_getNumberTagsForUserId,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IWebService_getStrenghtConnection
HRESULT WINAPI BasicHttpBinding_IWebService_getStrenghtConnection(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_ int id1, 
    _In_ int id2, 
    _In_opt_z_ WCHAR* user, 
    _In_opt_z_ WCHAR* pass, 
    _Out_ int* getStrenghtConnectionResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[5]; 
    _argList[0] = &id1;
    _argList[1] = &id2;
    _argList[2] = &user;
    _argList[3] = &pass;
    _argList[4] = &getStrenghtConnectionResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getStrenghtConnection.BasicHttpBinding_IWebService_getStrenghtConnection,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IWebService_getUserData
HRESULT WINAPI BasicHttpBinding_IWebService_getUserData(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_ int id, 
    _In_opt_z_ WCHAR* user, 
    _In_opt_z_ WCHAR* pass, 
    _Outptr_opt_ UserData** getUserDataResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[4]; 
    _argList[0] = &id;
    _argList[1] = &user;
    _argList[2] = &pass;
    _argList[3] = &getUserDataResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_getUserData.BasicHttpBinding_IWebService_getUserData,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IWebService_createFriendRequest
HRESULT WINAPI BasicHttpBinding_IWebService_createFriendRequest(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_ int id1, 
    _In_ int id2, 
    _In_opt_z_ WCHAR* user, 
    _In_opt_z_ WCHAR* pass, 
    _Out_ BOOL* createFriendRequestResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[5]; 
    _argList[0] = &id1;
    _argList[1] = &id2;
    _argList[2] = &user;
    _argList[3] = &pass;
    _argList[4] = &createFriendRequestResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.BasicHttpBinding_IWebService_createFriendRequest.BasicHttpBinding_IWebService_createFriendRequest,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}
#if (_MSC_VER >= 1400)
#pragma warning(pop)
#endif

const _tempuri_org_wsdl tempuri_org_wsdl =
{
    {  // messages
        {  // message description for IWebService_getNumberUsers_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getNumberUsers_InputMessageactionName, // http://tempuri.org/IWebService/getNumberUsers
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getNumberUsers, 
        },    // message description for IWebService_getNumberUsers_InputMessage
        {  // message description for IWebService_getNumberUsers_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getNumberUsers_OutputMessageactionName, // http://tempuri.org/IWebService/getNumberUsersResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getNumberUsersResponse, 
        },    // message description for IWebService_getNumberUsers_OutputMessage
        {  // message description for IWebService_getNumberDownloads_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getNumberDownloads_InputMessageactionName, // http://tempuri.org/IWebService/getNumberDownloads
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getNumberDownloads, 
        },    // message description for IWebService_getNumberDownloads_InputMessage
        {  // message description for IWebService_getNumberDownloads_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getNumberDownloads_OutputMessageactionName, // http://tempuri.org/IWebService/getNumberDownloadsResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getNumberDownloadsResponse, 
        },    // message description for IWebService_getNumberDownloads_OutputMessage
        {  // message description for IWebService_getUserByID_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getUserByID_InputMessageactionName, // http://tempuri.org/IWebService/getUserByID
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getUserByID, 
        },    // message description for IWebService_getUserByID_InputMessage
        {  // message description for IWebService_getUserByID_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getUserByID_OutputMessageactionName, // http://tempuri.org/IWebService/getUserByIDResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getUserByIDResponse, 
        },    // message description for IWebService_getUserByID_OutputMessage
        {  // message description for IWebService_getUserFriendsByUserId_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getUserFriendsByUserId_InputMessageactionName, // http://tempuri.org/IWebService/getUserFriendsByUserId
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getUserFriendsByUserId, 
        },    // message description for IWebService_getUserFriendsByUserId_InputMessage
        {  // message description for IWebService_getUserFriendsByUserId_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getUserFriendsByUserId_OutputMessageactionName, // http://tempuri.org/IWebService/getUserFriendsByUserIdResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getUserFriendsByUserIdResponse, 
        },    // message description for IWebService_getUserFriendsByUserId_OutputMessage
        {  // message description for IWebService_getUserByAutetication_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getUserByAutetication_InputMessageactionName, // http://tempuri.org/IWebService/getUserByAutetication
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getUserByAutetication, 
        },    // message description for IWebService_getUserByAutetication_InputMessage
        {  // message description for IWebService_getUserByAutetication_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getUserByAutetication_OutputMessageactionName, // http://tempuri.org/IWebService/getUserByAuteticationResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getUserByAuteticationResponse, 
        },    // message description for IWebService_getUserByAutetication_OutputMessage
        {  // message description for IWebService_GetEveryWord_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_GetEveryWord_InputMessageactionName, // http://tempuri.org/IWebService/GetEveryWord
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.GetEveryWord, 
        },    // message description for IWebService_GetEveryWord_InputMessage
        {  // message description for IWebService_GetEveryWord_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_GetEveryWord_OutputMessageactionName, // http://tempuri.org/IWebService/GetEveryWordResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.GetEveryWordResponse, 
        },    // message description for IWebService_GetEveryWord_OutputMessage
        {  // message description for IWebService_getAllUsersID_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getAllUsersID_InputMessageactionName, // http://tempuri.org/IWebService/getAllUsersID
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getAllUsersID, 
        },    // message description for IWebService_getAllUsersID_InputMessage
        {  // message description for IWebService_getAllUsersID_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getAllUsersID_OutputMessageactionName, // http://tempuri.org/IWebService/getAllUsersIDResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getAllUsersIDResponse, 
        },    // message description for IWebService_getAllUsersID_OutputMessage
        {  // message description for IWebService_getConnectioStrenght_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getConnectioStrenght_InputMessageactionName, // http://tempuri.org/IWebService/getConnectioStrenght
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getConnectioStrenght, 
        },    // message description for IWebService_getConnectioStrenght_InputMessage
        {  // message description for IWebService_getConnectioStrenght_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getConnectioStrenght_OutputMessageactionName, // http://tempuri.org/IWebService/getConnectioStrenghtResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getConnectioStrenghtResponse, 
        },    // message description for IWebService_getConnectioStrenght_OutputMessage
        {  // message description for IWebService_getNumberTagsForUserId_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getNumberTagsForUserId_InputMessageactionName, // http://tempuri.org/IWebService/getNumberTagsForUserId
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getNumberTagsForUserId, 
        },    // message description for IWebService_getNumberTagsForUserId_InputMessage
        {  // message description for IWebService_getNumberTagsForUserId_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getNumberTagsForUserId_OutputMessageactionName, // http://tempuri.org/IWebService/getNumberTagsForUserIdResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getNumberTagsForUserIdResponse, 
        },    // message description for IWebService_getNumberTagsForUserId_OutputMessage
        {  // message description for IWebService_getStrenghtConnection_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getStrenghtConnection_InputMessageactionName, // http://tempuri.org/IWebService/getStrenghtConnection
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getStrenghtConnection, 
        },    // message description for IWebService_getStrenghtConnection_InputMessage
        {  // message description for IWebService_getStrenghtConnection_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getStrenghtConnection_OutputMessageactionName, // http://tempuri.org/IWebService/getStrenghtConnectionResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getStrenghtConnectionResponse, 
        },    // message description for IWebService_getStrenghtConnection_OutputMessage
        {  // message description for IWebService_getUserData_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getUserData_InputMessageactionName, // http://tempuri.org/IWebService/getUserData
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getUserData, 
        },    // message description for IWebService_getUserData_InputMessage
        {  // message description for IWebService_getUserData_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_getUserData_OutputMessageactionName, // http://tempuri.org/IWebService/getUserDataResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.getUserDataResponse, 
        },    // message description for IWebService_getUserData_OutputMessage
        {  // message description for IWebService_createFriendRequest_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_createFriendRequest_InputMessageactionName, // http://tempuri.org/IWebService/createFriendRequest
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.createFriendRequest, 
        },    // message description for IWebService_createFriendRequest_InputMessage
        {  // message description for IWebService_createFriendRequest_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IWebService_createFriendRequest_OutputMessageactionName, // http://tempuri.org/IWebService/createFriendRequestResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.createFriendRequestResponse, 
        },    // message description for IWebService_createFriendRequest_OutputMessage
    },  // messages
    {  // contracts
        {  // BasicHttpBinding_IWebService
            12,
            (WS_OPERATION_DESCRIPTION**)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IWebService.operations,
        },  // end of BasicHttpBinding_IWebService
    },  // contracts
    {  // policies
        {  // template description for BasicHttpBinding_IWebService
            {  // channel properties
                (WS_CHANNEL_PROPERTY*)&tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IWebService.channelPropertiesArray,
                3,
            },
        },  // end of template description
    },  // policies
}; // end of _tempuri_org_wsdl

HRESULT BasicHttpBinding_IWebService_CreateServiceProxy(
    _In_opt_ WS_HTTP_BINDING_TEMPLATE* templateValue,
    _In_reads_opt_(proxyPropertyCount) const WS_PROXY_PROPERTY* proxyProperties,
    _In_ const ULONG proxyPropertyCount,
    _Outptr_ WS_SERVICE_PROXY** _serviceProxy,
    _In_opt_ WS_ERROR* error)
{
    return WsCreateServiceProxyFromTemplate(
        WS_CHANNEL_TYPE_REQUEST,
        proxyProperties,
        proxyPropertyCount,
        WS_HTTP_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_BINDING_TEMPLATE),
        &tempuri_org_wsdl.policies.BasicHttpBinding_IWebService,
        sizeof(tempuri_org_wsdl.policies.BasicHttpBinding_IWebService),
        _serviceProxy,
        error);
}

HRESULT BasicHttpBinding_IWebService_CreateServiceEndpoint(
    _In_opt_ WS_HTTP_BINDING_TEMPLATE* templateValue,
    _In_opt_ CONST WS_STRING* address,
    _In_opt_ struct BasicHttpBinding_IWebServiceFunctionTable* functionTable,
    _In_opt_ WS_SERVICE_SECURITY_CALLBACK authorizationCallback,
    _In_reads_opt_(endpointPropertyCount) WS_SERVICE_ENDPOINT_PROPERTY* endpointProperties,
    _In_ const ULONG endpointPropertyCount,
    _In_ WS_HEAP* heap,
    _Outptr_ WS_SERVICE_ENDPOINT** serviceEndpoint,
    _In_opt_ WS_ERROR* error)
{
    WS_SERVICE_CONTRACT serviceContract;
    serviceContract.contractDescription = &tempuri_org_wsdl.contracts.BasicHttpBinding_IWebService;
    serviceContract.defaultMessageHandlerCallback = 0;
    serviceContract.methodTable = (const void*)functionTable;
    
    return WsCreateServiceEndpointFromTemplate(
        WS_CHANNEL_TYPE_REPLY,
        endpointProperties,
        endpointPropertyCount,
        address,
        &serviceContract,
        authorizationCallback,
        heap,
        WS_HTTP_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_BINDING_TEMPLATE),
        &tempuri_org_wsdl.policies.BasicHttpBinding_IWebService,
        sizeof(tempuri_org_wsdl.policies.BasicHttpBinding_IWebService),
        serviceEndpoint,
        error);
}
