//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicWareWeb.Views.User {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class User {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EpicWareWeb.Views.User.User", typeof(User).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceitar Amigo.
        /// </summary>
        public static string aceitar_amigo {
            get {
                return ResourceManager.GetString("aceitar_amigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar Amigo.
        /// </summary>
        public static string adicionar_amigo {
            get {
                return ResourceManager.GetString("adicionar_amigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido de amizade pendente.
        /// </summary>
        public static string amizade_pendente {
            get {
                return ResourceManager.GetString("amizade_pendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aniversário.
        /// </summary>
        public static string aniversario {
            get {
                return ResourceManager.GetString("aniversario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sua conta de utilizador encontra-se inativa! Pretende reativa-la?.
        /// </summary>
        public static string avisoContaDesativada {
            get {
                return ResourceManager.GetString("avisoContaDesativada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem a certeza que pretende desativar a conta de utilizador?.
        /// </summary>
        public static string confirmDesativarConta {
            get {
                return ResourceManager.GetString("confirmDesativarConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Perfil.
        /// </summary>
        public static string edit_perfil {
            get {
                return ResourceManager.GetString("edit_perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feliz.
        /// </summary>
        public static string feliz {
            get {
                return ResourceManager.GetString("feliz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feminino.
        /// </summary>
        public static string feminino {
            get {
                return ResourceManager.GetString("feminino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Género.
        /// </summary>
        public static string genero {
            get {
                return ResourceManager.GetString("genero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora.
        /// </summary>
        public static string hora {
            get {
                return ResourceManager.GetString("hora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado de Humor.
        /// </summary>
        public static string humor {
            get {
                return ResourceManager.GetString("humor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedido Introdução Enviado.
        /// </summary>
        public static string introEnviada {
            get {
                return ResourceManager.GetString("introEnviada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lida.
        /// </summary>
        public static string lida {
            get {
                return ResourceManager.GetString("lida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masculino.
        /// </summary>
        public static string masculino {
            get {
                return ResourceManager.GetString("masculino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagem.
        /// </summary>
        public static string mensagem {
            get {
                return ResourceManager.GetString("mensagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string nao {
            get {
                return ResourceManager.GetString("nao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nickname.
        /// </summary>
        public static string nick {
            get {
                return ResourceManager.GetString("nick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string normal {
            get {
                return ResourceManager.GetString("normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificações.
        /// </summary>
        public static string notificacoes {
            get {
                return ResourceManager.GetString("notificacoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo pedido de amizade.
        /// </summary>
        public static string novopedidoamizade {
            get {
                return ResourceManager.GetString("novopedidoamizade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo pedido de introdução.
        /// </summary>
        public static string novopedidointroducao {
            get {
                return ResourceManager.GetString("novopedidointroducao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string pais {
            get {
                return ResourceManager.GetString("pais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedir Introdução.
        /// </summary>
        public static string pedir_intro {
            get {
                return ResourceManager.GetString("pedir_intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string perfil {
            get {
                return ResourceManager.GetString("perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reativar Conta.
        /// </summary>
        public static string reativarConta {
            get {
                return ResourceManager.GetString("reativarConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sem Imagem .
        /// </summary>
        public static string semimagem {
            get {
                return ResourceManager.GetString("semimagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string sim {
            get {
                return ResourceManager.GetString("sim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        public static string social {
            get {
                return ResourceManager.GetString("social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separado por &apos;,&apos;.
        /// </summary>
        public static string textoDefaultTags {
            get {
                return ResourceManager.GetString("textoDefaultTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triste.
        /// </summary>
        public static string triste {
            get {
                return ResourceManager.GetString("triste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver.
        /// </summary>
        public static string ver {
            get {
                return ResourceManager.GetString("ver", resourceCulture);
            }
        }
    }
}
