
// File generated by Wsutil Compiler version 1.0095 
#include <WebServices.h>
#include "SocialGameService.xsd.h"

typedef struct _SocialGameService_xsdLocalDefinitions 
{
    struct  // global types
    {
        char unused;
        struct  // ArrayOfWord
        {
            struct  // Word
            {
                WS_FIELD_DESCRIPTION language;
                WS_FIELD_DESCRIPTION text;
                WS_FIELD_DESCRIPTION topic;
                WS_FIELD_DESCRIPTION* WordFields [3]; 
            } Worddescs; // end of Word
            WS_FIELD_DESCRIPTION Word;
            WS_FIELD_DESCRIPTION* ArrayOfWordFields [1]; 
        } ArrayOfWorddescs; // end of ArrayOfWord
    } globalTypes;  // end of global types
    struct  // XML dictionary
    {
        struct  // XML string list
        {
            WS_XML_STRING ArrayOfWordTypeName;  // ArrayOfWord
            WS_XML_STRING ArrayOfWordTypeNamespace;  // http://schemas.datacontract.org/2004/07/SocialGameService
            WS_XML_STRING WordTypeName;  // Word
            WS_XML_STRING WordlanguageLocalName;  // language
            WS_XML_STRING WordtextLocalName;  // text
            WS_XML_STRING WordtopicLocalName;  // topic
        } xmlStrings;  // end of XML string list
        WS_XML_DICTIONARY dict;
    } dictionary;  // end of XML dictionary
} _SocialGameService_xsdLocalDefinitions;

const static _SocialGameService_xsdLocalDefinitions SocialGameService_xsdLocalDefinitions =
{
    { // global types
        0,
        {  // ArrayOfWord
            {  // Word
                {  // field description for language
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&SocialGameService_xsdLocalDefinitions.dictionary.xmlStrings.WordlanguageLocalName, // language
                (WS_XML_STRING*)&SocialGameService_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfWordTypeNamespace, // http://schemas.datacontract.org/2004/07/SocialGameService
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(Word, language),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for language
                {  // field description for text
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&SocialGameService_xsdLocalDefinitions.dictionary.xmlStrings.WordtextLocalName, // text
                (WS_XML_STRING*)&SocialGameService_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfWordTypeNamespace, // http://schemas.datacontract.org/2004/07/SocialGameService
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(Word, text),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for text
                {  // field description for topic
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&SocialGameService_xsdLocalDefinitions.dictionary.xmlStrings.WordtopicLocalName, // topic
                (WS_XML_STRING*)&SocialGameService_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfWordTypeNamespace, // http://schemas.datacontract.org/2004/07/SocialGameService
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(Word, topic),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for topic
                {  // fields description for Word
                (WS_FIELD_DESCRIPTION*)&SocialGameService_xsdLocalDefinitions.globalTypes.ArrayOfWorddescs.Worddescs.language,
                (WS_FIELD_DESCRIPTION*)&SocialGameService_xsdLocalDefinitions.globalTypes.ArrayOfWorddescs.Worddescs.text,
                (WS_FIELD_DESCRIPTION*)&SocialGameService_xsdLocalDefinitions.globalTypes.ArrayOfWorddescs.Worddescs.topic,
                },
            },    // Word
            {  // field description for Word
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            0,
            0,
            WS_STRUCT_TYPE,
            (void*)&SocialGameService_xsd.globalTypes.Word,
            WsOffsetOf(ArrayOfWord, Word),
            0,
            0,
            WsOffsetOf(ArrayOfWord, WordCount),
            (WS_XML_STRING*)&SocialGameService_xsdLocalDefinitions.dictionary.xmlStrings.WordTypeName, // Word
            (WS_XML_STRING*)&SocialGameService_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfWordTypeNamespace, // http://schemas.datacontract.org/2004/07/SocialGameService
            0,
            },    // end of field description for Word
            {  // fields description for ArrayOfWord
            (WS_FIELD_DESCRIPTION*)&SocialGameService_xsdLocalDefinitions.globalTypes.ArrayOfWorddescs.Word,
            },
        },    // ArrayOfWord
    }, // end of global types
    {  // dictionary 
        {  // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("ArrayOfWord",&SocialGameService_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.datacontract.org/2004/07/SocialGameService",&SocialGameService_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("Word",&SocialGameService_xsdLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("language",&SocialGameService_xsdLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("text",&SocialGameService_xsdLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("topic",&SocialGameService_xsdLocalDefinitions.dictionary.dict, 5),
        },  // end of xmlStrings
        
        {  // SocialGameService_xsddictionary
          // ea40b7b0-4e7b-4d1e-95de-5352a7977e95 
        { 0xea40b7b0, 0x4e7b, 0x4d1e, { 0x95, 0xde, 0x53,0x52, 0xa7, 0x97, 0x7e, 0x95 } },
        (WS_XML_STRING*)&SocialGameService_xsdLocalDefinitions.dictionary.xmlStrings,
        6,
        TRUE,
        },
    },  //  end of dictionary
}; //  end of SocialGameService_xsdLocalDefinitions

const _SocialGameService_xsd SocialGameService_xsd =
{
    {  // globalTypes
        {
        sizeof(ArrayOfWord),
        __alignof(ArrayOfWord),
        (WS_FIELD_DESCRIPTION**)&SocialGameService_xsdLocalDefinitions.globalTypes.ArrayOfWorddescs.ArrayOfWordFields,
        WsCountOf(SocialGameService_xsdLocalDefinitions.globalTypes.ArrayOfWorddescs.ArrayOfWordFields),
        (WS_XML_STRING*)&SocialGameService_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfWordTypeName, // ArrayOfWord
        (WS_XML_STRING*)&SocialGameService_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfWordTypeNamespace, // http://schemas.datacontract.org/2004/07/SocialGameService
        0,
        0,
        0,
        },   // end of struct description for ArrayOfWord
        {
        sizeof(Word),
        __alignof(Word),
        (WS_FIELD_DESCRIPTION**)&SocialGameService_xsdLocalDefinitions.globalTypes.ArrayOfWorddescs.Worddescs.WordFields,
        WsCountOf(SocialGameService_xsdLocalDefinitions.globalTypes.ArrayOfWorddescs.Worddescs.WordFields),
        (WS_XML_STRING*)&SocialGameService_xsdLocalDefinitions.dictionary.xmlStrings.WordTypeName, // Word
        (WS_XML_STRING*)&SocialGameService_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfWordTypeNamespace, // http://schemas.datacontract.org/2004/07/SocialGameService
        0,
        0,
        0,
        },   // end of struct description for Word
    },  // globalTypes
    {  // globalElements
        {
            (WS_XML_STRING*)&SocialGameService_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfWordTypeName, // ArrayOfWord
            (WS_XML_STRING*)&SocialGameService_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfWordTypeNamespace, // http://schemas.datacontract.org/2004/07/SocialGameService
            WS_STRUCT_TYPE,
            (void*)&SocialGameService_xsd.globalTypes.ArrayOfWord,
        },
        {
            (WS_XML_STRING*)&SocialGameService_xsdLocalDefinitions.dictionary.xmlStrings.WordTypeName, // Word
            (WS_XML_STRING*)&SocialGameService_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfWordTypeNamespace, // http://schemas.datacontract.org/2004/07/SocialGameService
            WS_STRUCT_TYPE,
            (void*)&SocialGameService_xsd.globalTypes.Word,
        },
    },  // globalElements
}; // end of _SocialGameService_xsd
