
// File generated by Wsutil Compiler version 1.0095 
#include <WebServices.h>
#include "SocialGameService.xsd.h"
#include "tempuri.org.xsd.h"

typedef struct _tempuri_org_xsdLocalDefinitions 
{
    struct  // global elements
    {
    char unused;
        struct  // _GetEveryWordResponse
        {
            WS_FIELD_DESCRIPTION GetEveryWordResult;
            WS_FIELD_DESCRIPTION* _GetEveryWordResponseFields [1]; 
        } _GetEveryWordResponsedescs; // end of _GetEveryWordResponse
        struct  // _Add
        {
            WS_FIELD_DESCRIPTION x;
            WS_FIELD_DESCRIPTION y;
            WS_FIELD_DESCRIPTION* _AddFields [2]; 
        } _Adddescs; // end of _Add
        struct  // _AddResponse
        {
            WS_FIELD_DESCRIPTION AddResult;
            WS_FIELD_DESCRIPTION* _AddResponseFields [1]; 
        } _AddResponsedescs; // end of _AddResponse
    } globalElements;  // end of global elements
    struct  // XML dictionary
    {
        struct  // XML string list
        {
            WS_XML_STRING _GetEveryWordTypeName;  // GetEveryWord
            WS_XML_STRING _GetEveryWordTypeNamespace;  // http://tempuri.org/
            WS_XML_STRING _GetEveryWordResponseTypeName;  // GetEveryWordResponse
            WS_XML_STRING _GetEveryWordResponseGetEveryWordResultLocalName;  // Word
            WS_XML_STRING _GetEveryWordResponseGetEveryWordResultNamespace;  // http://schemas.datacontract.org/2004/07/SocialGameService
            WS_XML_STRING _GetEveryWordResponseGetEveryWordResultWrapperName;  // GetEveryWordResult
            WS_XML_STRING _AddTypeName;  // Add
            WS_XML_STRING _AddxLocalName;  // x
            WS_XML_STRING _AddyLocalName;  // y
            WS_XML_STRING _AddResponseTypeName;  // AddResponse
            WS_XML_STRING _AddResponseAddResultLocalName;  // AddResult
        } xmlStrings;  // end of XML string list
        WS_XML_DICTIONARY dict;
    } dictionary;  // end of XML dictionary
} _tempuri_org_xsdLocalDefinitions;

const static _tempuri_org_xsdLocalDefinitions tempuri_org_xsdLocalDefinitions =
{
    {  // global elements
        0,
        {  // _GetEveryWordResponse
            {  // field description for GetEveryWordResult
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetEveryWordResponseGetEveryWordResultWrapperName, // GetEveryWordResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetEveryWordTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&SocialGameService_xsd.globalTypes.Word,
            WsOffsetOf(_GetEveryWordResponse, GetEveryWordResult),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            WsOffsetOf(_GetEveryWordResponse, GetEveryWordResultCount),
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetEveryWordResponseGetEveryWordResultLocalName, // Word
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetEveryWordResponseGetEveryWordResultNamespace, // http://schemas.datacontract.org/2004/07/SocialGameService
            0,
            },    // end of field description for GetEveryWordResult
            {  // fields description for _GetEveryWordResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._GetEveryWordResponsedescs.GetEveryWordResult,
            },
        },    // _GetEveryWordResponse
        {  // _Add
            {  // field description for x
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddxLocalName, // x
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetEveryWordTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_Add, x),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for x
            {  // field description for y
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddyLocalName, // y
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetEveryWordTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_Add, y),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for y
            {  // fields description for _Add
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._Adddescs.x,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._Adddescs.y,
            },
        },    // _Add
        {  // _AddResponse
            {  // field description for AddResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddResponseAddResultLocalName, // AddResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetEveryWordTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_AddResponse, AddResult),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for AddResult
            {  // fields description for _AddResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._AddResponsedescs.AddResult,
            },
        },    // _AddResponse
    }, // end of global elements
    {  // dictionary 
        {  // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("GetEveryWord",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("GetEveryWordResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("Word",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.datacontract.org/2004/07/SocialGameService",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("GetEveryWordResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("Add",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("x",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 7),
            WS_XML_STRING_DICTIONARY_VALUE("y",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 8),
            WS_XML_STRING_DICTIONARY_VALUE("AddResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 9),
            WS_XML_STRING_DICTIONARY_VALUE("AddResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 10),
        },  // end of xmlStrings
        
        {  // tempuri_org_xsddictionary
          // dae4128f-2b52-4da2-9141-a9709ab7d06d 
        { 0xdae4128f, 0x2b52, 0x4da2, { 0x91, 0x41, 0xa9,0x70, 0x9a, 0xb7, 0xd0, 0x6d } },
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings,
        11,
        TRUE,
        },
    },  //  end of dictionary
}; //  end of tempuri_org_xsdLocalDefinitions

const _tempuri_org_xsd tempuri_org_xsd =
{
    {  // globalElements
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetEveryWordTypeName, // GetEveryWord
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetEveryWordTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.GetEveryWord,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetEveryWordResponseTypeName, // GetEveryWordResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetEveryWordTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.GetEveryWordResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeName, // Add
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetEveryWordTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.Add,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddResponseTypeName, // AddResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetEveryWordTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.AddResponse,
        },
    },  // globalElements
    {  // begin of externallyReferencedTypes
        {
        0,
        1,
        0,
        0,
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetEveryWordTypeName, // GetEveryWord
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetEveryWordTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _GetEveryWord
        {
        sizeof(_GetEveryWordResponse),
        __alignof(_GetEveryWordResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._GetEveryWordResponsedescs._GetEveryWordResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._GetEveryWordResponsedescs._GetEveryWordResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetEveryWordResponseTypeName, // GetEveryWordResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetEveryWordTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _GetEveryWordResponse
        {
        sizeof(_Add),
        __alignof(_Add),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._Adddescs._AddFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._Adddescs._AddFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeName, // Add
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetEveryWordTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _Add
        {
        sizeof(_AddResponse),
        __alignof(_AddResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._AddResponsedescs._AddResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._AddResponsedescs._AddResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddResponseTypeName, // AddResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetEveryWordTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _AddResponse
    },  // end of externallyReferencedTypes;
}; // end of _tempuri_org_xsd
