
// File generated by Wsutil Compiler version 1.0095 
#include <WebServices.h>
#include "SocialGameService.xsd.h"
#include "tempuri.org.xsd.h"
#include "tempuri.org.wsdl.h"

typedef struct _tempuri_org_wsdlLocalDefinitions 
{
    struct  // messages
    {
        WS_MESSAGE_DESCRIPTION IService1_GetEveryWord_InputMessage;
        WS_MESSAGE_DESCRIPTION IService1_GetEveryWord_OutputMessage;
        WS_MESSAGE_DESCRIPTION IService1_Add_InputMessage;
        WS_MESSAGE_DESCRIPTION IService1_Add_OutputMessage;
    } messages;  // end of messages
    struct  // contracts
    {
        struct  // BasicHttpBinding_IService1
        {
            struct  // BasicHttpBinding_IService1_GetEveryWord
            {
                WS_PARAMETER_DESCRIPTION params[2];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IService1_GetEveryWord;
            } BasicHttpBinding_IService1_GetEveryWord;
            struct  // BasicHttpBinding_IService1_Add
            {
                WS_PARAMETER_DESCRIPTION params[3];
                WS_OPERATION_DESCRIPTION BasicHttpBinding_IService1_Add;
            } BasicHttpBinding_IService1_Add;
            WS_OPERATION_DESCRIPTION* operations[2];
            WS_CONTRACT_DESCRIPTION contractDesc;
        } BasicHttpBinding_IService1;
    } contracts;  // endof contracts 
    struct  // policies
    {
        struct  // BasicHttpBinding_IService1
        {
            WS_ENCODING encoding;
            WS_ADDRESSING_VERSION addressingVersion;
            WS_ENVELOPE_VERSION envelopeVersion;
            WS_CHANNEL_PROPERTY channelPropertiesArray[3];
        } BasicHttpBinding_IService1;
    } policies;
    struct  // XML dictionary
    {
        struct  // XML string list
        {
            WS_XML_STRING IService1_GetEveryWord_InputMessageactionName;  // http://tempuri.org/IService1/GetEveryWord
            WS_XML_STRING IService1_GetEveryWord_OutputMessageactionName;  // http://tempuri.org/IService1/GetEveryWordResponse
            WS_XML_STRING IService1_Add_InputMessageactionName;  // http://tempuri.org/IService1/Add
            WS_XML_STRING IService1_Add_OutputMessageactionName;  // http://tempuri.org/IService1/AddResponse
        } xmlStrings;  // end of XML string list
        WS_XML_DICTIONARY dict;
    } dictionary;  // end of XML dictionary
} _tempuri_org_wsdlLocalDefinitions;


typedef struct BasicHttpBinding_IService1_GetEveryWordParamStruct 
{
    unsigned int* GetEveryWordResultCount;
    Word** GetEveryWordResult;
} BasicHttpBinding_IService1_GetEveryWordParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IService1_GetEveryWordOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IService1_GetEveryWordCallback _operation = (BasicHttpBinding_IService1_GetEveryWordCallback)_callback;
    BasicHttpBinding_IService1_GetEveryWordParamStruct *_stack =(BasicHttpBinding_IService1_GetEveryWordParamStruct*)_stackStruct;
    return _operation( 
        _context,
        _stack->GetEveryWordResultCount,
        (_stack->GetEveryWordResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif

typedef struct BasicHttpBinding_IService1_AddParamStruct 
{
    int* x;
    int* y;
    int* AddResult;
} BasicHttpBinding_IService1_AddParamStruct;

#if (_MSC_VER >=1400) 
#pragma warning(push)
#endif
#pragma warning(disable: 4055) // conversion from data pointer to function pointer
HRESULT CALLBACK BasicHttpBinding_IService1_AddOperationStub(
    _In_ const WS_OPERATION_CONTEXT* _context,
    _In_ void* _stackStruct,
    _In_ const void* _callback,
    _In_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_ WS_ERROR* _error)
{
    BasicHttpBinding_IService1_AddCallback _operation = (BasicHttpBinding_IService1_AddCallback)_callback;
    BasicHttpBinding_IService1_AddParamStruct *_stack =(BasicHttpBinding_IService1_AddParamStruct*)_stackStruct;
    return _operation( 
        _context,
        *(_stack->x),
        *(_stack->y),
        (_stack->AddResult),
        (WS_ASYNC_CONTEXT*)_asyncContext,
        _error);
}
#pragma warning(default: 4055)  // conversion from data pointer to function pointer
#if (_MSC_VER >=1400) 
#pragma warning(pop)
#endif
const static _tempuri_org_wsdlLocalDefinitions tempuri_org_wsdlLocalDefinitions =
{
    {  // messages
        {  // message description for IService1_GetEveryWord_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IService1_GetEveryWord_InputMessageactionName, // http://tempuri.org/IService1/GetEveryWord
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.GetEveryWord, 
        },    // message description for IService1_GetEveryWord_InputMessage
        {  // message description for IService1_GetEveryWord_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IService1_GetEveryWord_OutputMessageactionName, // http://tempuri.org/IService1/GetEveryWordResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.GetEveryWordResponse, 
        },    // message description for IService1_GetEveryWord_OutputMessage
        {  // message description for IService1_Add_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IService1_Add_InputMessageactionName, // http://tempuri.org/IService1/Add
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.Add, 
        },    // message description for IService1_Add_InputMessage
        {  // message description for IService1_Add_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IService1_Add_OutputMessageactionName, // http://tempuri.org/IService1/AddResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.AddResponse, 
        },    // message description for IService1_Add_OutputMessage
    },  // end of messages 
    {  // contracts
        {  // BasicHttpBinding_IService1,
            {  // BasicHttpBinding_IService1_GetEveryWord
                {  // parameter descriptions for BasicHttpBinding_IService1_GetEveryWord
                    {WS_PARAMETER_TYPE_ARRAY_COUNT, (USHORT)-1, (USHORT)0},
                    {WS_PARAMETER_TYPE_ARRAY, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IService1_GetEveryWord
                {  // operation description for BasicHttpBinding_IService1_GetEveryWord
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IService1_GetEveryWord_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IService1_GetEveryWord_OutputMessage, 
                    0,
                    0,
                    2,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IService1.BasicHttpBinding_IService1_GetEveryWord.params,
                    BasicHttpBinding_IService1_GetEveryWordOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IService1_GetEveryWord
            },  // BasicHttpBinding_IService1_GetEveryWord
            {  // BasicHttpBinding_IService1_Add
                {  // parameter descriptions for BasicHttpBinding_IService1_Add
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)0, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)1, (USHORT)-1},
                    {WS_PARAMETER_TYPE_NORMAL, (USHORT)-1, (USHORT)0},
                },  // parameter descriptions for BasicHttpBinding_IService1_Add
                {  // operation description for BasicHttpBinding_IService1_Add
                    1,
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IService1_Add_InputMessage, 
                    (WS_MESSAGE_DESCRIPTION*)&tempuri_org_wsdl.messages.IService1_Add_OutputMessage, 
                    0,
                    0,
                    3,
                    (WS_PARAMETER_DESCRIPTION*)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IService1.BasicHttpBinding_IService1_Add.params,
                    BasicHttpBinding_IService1_AddOperationStub,
                    WS_NON_RPC_LITERAL_OPERATION
                }, //operation description for BasicHttpBinding_IService1_Add
            },  // BasicHttpBinding_IService1_Add
            {  // array of operations for BasicHttpBinding_IService1
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IService1.BasicHttpBinding_IService1_GetEveryWord.BasicHttpBinding_IService1_GetEveryWord,
                (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IService1.BasicHttpBinding_IService1_Add.BasicHttpBinding_IService1_Add,
            },  // array of operations for BasicHttpBinding_IService1
            {  // contract description for BasicHttpBinding_IService1
            2,
            (WS_OPERATION_DESCRIPTION**)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IService1.operations,
            },  // end of contract description for BasicHttpBinding_IService1
        },  // BasicHttpBinding_IService1
    },  // end of contracts 
    {  // policies
        {
            WS_ENCODING_XML_UTF8,
            WS_ADDRESSING_VERSION_TRANSPORT,
            WS_ENVELOPE_VERSION_SOAP_1_1,
            { // channelPropertiesArray
                {
                    WS_CHANNEL_PROPERTY_ENCODING,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IService1.encoding,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IService1.encoding),
                },
                {
                    WS_CHANNEL_PROPERTY_ADDRESSING_VERSION,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IService1.addressingVersion,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IService1.addressingVersion),
                },
                {
                    WS_CHANNEL_PROPERTY_ENVELOPE_VERSION,
                    (void*)&tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IService1.envelopeVersion,
                    sizeof(tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IService1.envelopeVersion),
                },
            },
        },   // end of BasicHttpBinding_IService1,
    }, // policies
    {  // dictionary 
        {  // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IService1/GetEveryWord",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IService1/GetEveryWordResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IService1/Add",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/IService1/AddResponse",&tempuri_org_wsdlLocalDefinitions.dictionary.dict, 3),
        },  // end of xmlStrings
        
        {  // tempuri_org_wsdldictionary
          // a8636042-5cbc-421a-a0b2-bcd485b2515e 
        { 0xa8636042, 0x5cbc, 0x421a, { 0xa0, 0xb2, 0xbc,0xd4, 0x85, 0xb2, 0x51, 0x5e } },
        (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings,
        4,
        TRUE,
        },
    },  //  end of dictionary
}; //  end of tempuri_org_wsdlLocalDefinitions

// Disable prefast warnings for the output parameters as their contract cannot be expressed in SAL.
#if (_MSC_VER >= 1400)
#pragma warning(push)
#endif
#pragma warning(disable: 6101 6054)

// operation: BasicHttpBinding_IService1_GetEveryWord
HRESULT WINAPI BasicHttpBinding_IService1_GetEveryWord(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _Out_ unsigned int* GetEveryWordResultCount, 
    _Outptr_opt_result_buffer_(*GetEveryWordResultCount) Word** GetEveryWordResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[2]; 
    _argList[0] = &GetEveryWordResultCount;
    _argList[1] = &GetEveryWordResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IService1.BasicHttpBinding_IService1_GetEveryWord.BasicHttpBinding_IService1_GetEveryWord,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}

// operation: BasicHttpBinding_IService1_Add
HRESULT WINAPI BasicHttpBinding_IService1_Add(
    _In_ WS_SERVICE_PROXY* _serviceProxy,
    _In_ int x, 
    _In_ int y, 
    _Out_ int* AddResult, 
    _In_ WS_HEAP* _heap,
    _In_reads_opt_(_callPropertyCount) const WS_CALL_PROPERTY* _callProperties,
    _In_ const ULONG _callPropertyCount,
    _In_opt_ const WS_ASYNC_CONTEXT* _asyncContext,
    _In_opt_ WS_ERROR* _error)
{
    void* _argList[3]; 
    _argList[0] = &x;
    _argList[1] = &y;
    _argList[2] = &AddResult;
    return WsCall(_serviceProxy,
        (WS_OPERATION_DESCRIPTION*)&tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IService1.BasicHttpBinding_IService1_Add.BasicHttpBinding_IService1_Add,
        (const void **)&_argList,
        _heap,
        _callProperties,
        _callPropertyCount,
        _asyncContext,
        _error);
}
#if (_MSC_VER >= 1400)
#pragma warning(pop)
#endif

const _tempuri_org_wsdl tempuri_org_wsdl =
{
    {  // messages
        {  // message description for IService1_GetEveryWord_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IService1_GetEveryWord_InputMessageactionName, // http://tempuri.org/IService1/GetEveryWord
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.GetEveryWord, 
        },    // message description for IService1_GetEveryWord_InputMessage
        {  // message description for IService1_GetEveryWord_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IService1_GetEveryWord_OutputMessageactionName, // http://tempuri.org/IService1/GetEveryWordResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.GetEveryWordResponse, 
        },    // message description for IService1_GetEveryWord_OutputMessage
        {  // message description for IService1_Add_InputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IService1_Add_InputMessageactionName, // http://tempuri.org/IService1/Add
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.Add, 
        },    // message description for IService1_Add_InputMessage
        {  // message description for IService1_Add_OutputMessage
            (WS_XML_STRING*)&tempuri_org_wsdlLocalDefinitions.dictionary.xmlStrings.IService1_Add_OutputMessageactionName, // http://tempuri.org/IService1/AddResponse
            (WS_ELEMENT_DESCRIPTION*)&tempuri_org_xsd.globalElements.AddResponse, 
        },    // message description for IService1_Add_OutputMessage
    },  // messages
    {  // contracts
        {  // BasicHttpBinding_IService1
            2,
            (WS_OPERATION_DESCRIPTION**)tempuri_org_wsdlLocalDefinitions.contracts.BasicHttpBinding_IService1.operations,
        },  // end of BasicHttpBinding_IService1
    },  // contracts
    {  // policies
        {  // template description for BasicHttpBinding_IService1
            {  // channel properties
                (WS_CHANNEL_PROPERTY*)&tempuri_org_wsdlLocalDefinitions.policies.BasicHttpBinding_IService1.channelPropertiesArray,
                3,
            },
        },  // end of template description
    },  // policies
}; // end of _tempuri_org_wsdl

HRESULT BasicHttpBinding_IService1_CreateServiceProxy(
    _In_opt_ WS_HTTP_BINDING_TEMPLATE* templateValue,
    _In_reads_opt_(proxyPropertyCount) const WS_PROXY_PROPERTY* proxyProperties,
    _In_ const ULONG proxyPropertyCount,
    _Outptr_ WS_SERVICE_PROXY** _serviceProxy,
    _In_opt_ WS_ERROR* error)
{
    return WsCreateServiceProxyFromTemplate(
        WS_CHANNEL_TYPE_REQUEST,
        proxyProperties,
        proxyPropertyCount,
        WS_HTTP_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_BINDING_TEMPLATE),
        &tempuri_org_wsdl.policies.BasicHttpBinding_IService1,
        sizeof(tempuri_org_wsdl.policies.BasicHttpBinding_IService1),
        _serviceProxy,
        error);
}

HRESULT BasicHttpBinding_IService1_CreateServiceEndpoint(
    _In_opt_ WS_HTTP_BINDING_TEMPLATE* templateValue,
    _In_opt_ CONST WS_STRING* address,
    _In_opt_ struct BasicHttpBinding_IService1FunctionTable* functionTable,
    _In_opt_ WS_SERVICE_SECURITY_CALLBACK authorizationCallback,
    _In_reads_opt_(endpointPropertyCount) WS_SERVICE_ENDPOINT_PROPERTY* endpointProperties,
    _In_ const ULONG endpointPropertyCount,
    _In_ WS_HEAP* heap,
    _Outptr_ WS_SERVICE_ENDPOINT** serviceEndpoint,
    _In_opt_ WS_ERROR* error)
{
    WS_SERVICE_CONTRACT serviceContract;
    serviceContract.contractDescription = &tempuri_org_wsdl.contracts.BasicHttpBinding_IService1;
    serviceContract.defaultMessageHandlerCallback = 0;
    serviceContract.methodTable = (const void*)functionTable;
    
    return WsCreateServiceEndpointFromTemplate(
        WS_CHANNEL_TYPE_REPLY,
        endpointProperties,
        endpointPropertyCount,
        address,
        &serviceContract,
        authorizationCallback,
        heap,
        WS_HTTP_BINDING_TEMPLATE_TYPE,
        templateValue,
        templateValue == NULL ? 0 : sizeof(WS_HTTP_BINDING_TEMPLATE),
        &tempuri_org_wsdl.policies.BasicHttpBinding_IService1,
        sizeof(tempuri_org_wsdl.policies.BasicHttpBinding_IService1),
        serviceEndpoint,
        error);
}
