// <auto-generated />
namespace EpicWareWeb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class moodAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(moodAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "201312171407170_moodAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
