// <auto-generated />
namespace EpicWareWeb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class profileUpd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(profileUpd));
        
        string IMigrationMetadata.Id
        {
            get { return "201312171544102_profileUpd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
