// <auto-generated />
namespace EpicWareWeb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201401121428341_updUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
