// <auto-generated />
namespace EpicWareWeb.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updNotification2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updNotification2));
        
        string IMigrationMetadata.Id
        {
            get { return "201401022353314_updNotification2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
